### ISSUE TITLE
libreoffice language installation

### ISSUE THREAD

**Issue by inukaze** [dslackw/slpkg#103]
Hi there, i just have the follow dunno : 
How i can install libreoffice in es-VE language pack and helppack ?

i try with
export LOLANG=es-VE ; LOLANG=es-VE slpkg -s sbo libreoffice-langpack libreoffice-helppack

ever fails because ever try to install "en-US" or "en-GB" but never my native language es-ve support.

 how i can use slpkg to install the language i wish for the libreoffice ?

**Comment by dslackw** [comment]
Hi @inukaze,

Can you try:
```
# export LibreOffice_LOLANG=es-VE
# slpkg -s sbo LibreOffice
```

**Comment by inukaze** [comment]
Work with : 

```
export libreoffice_LOLANG=es-VE ; libreoffice_LOLANG=es-ve
slpkg -s sbo libreoffice-langpack libreoffice-helppack
```
