### ISSUE TITLE
Dunno : how install multilib support with slpkg ?

### ISSUE THREAD

**Issue by inukaze** [dslackw/slpkg#104]
Hi there i recently had make a fresh install of Slackware64 14.2, reading the tutorials again -> https://docs.slackware.com/slackware:multilib

i have the dunno : 
How install multilib support with slpkg ?

Because i don't want to use "The quick 'n' dirty instructions" again. i prefer some more controlled by software package manager like slpkg.

How i can install every package (i suppose, i must enable "multi" repository) for do that. but i don't have idea what is the better command for make the package installation

**Comment by dslackw** [comment]
You can try:
```
# slpkg -s multi ""
```
