### ISSUE TITLE
slpkg dependencies.

### ISSUE THREAD

**Issue by bifferos** [dslackw/slpkg#105]
Not so much an issue as a request...

slpkg binaries install and work just fine on a full Slackware 14.2 install, but not on reduced  (A, AP, D, L, N disk sets).  For people trying to get away with less than a 10GB install set it would be nice to know what I'm actually missing.

There is some weird error from python that you get, and it was discussed here:
https://www.linuxquestions.org/questions/slackware-14/python%3B-importerror-no-module-named-slpkg-main-4175596249/

Any input about what would cause that error would be good.  I mean, it looks as though it is looking for a slpkg module which must surely be present!

**Comment by dslackw** [comment]
Hi @bifferos,
There is a file "requirements.txt" https://github.com/dslackw/slpkg/blob/master/requirements.txt
