### ISSUE TITLE
slpkg update slpkg "uri not found"

### ISSUE THREAD

**Issue by lupox** [dslackw/slpkg#108]
slpkg update slpkg

New version 'slpkg-3.3.5' is available !

Would you like to upgrade [y/N]? y

[1/1][ Download ] --> v3.3.5.tar.gz

04/20 18:06:37 [NOTICE] Downloading 1 item(s)

04/20 18:06:37 [NOTICE] CUID#7 - Redirecting to https://codeload.github.com/dslackw/slpkg/tar.gz/v3.3.5
[#f8aba5 0B/0B CN:1 DL:0B]                                                                                                                 
04/20 18:06:38 [ERROR] CUID#7 - Download aborted. URI=https://github.com/dslackw/slpkg/archive/v3.3.5.tar.gz
Exception: [AbstractCommand.cc:351] errorCode=3 URI=https://codeload.github.com/dslackw/slpkg/tar.gz/v3.3.5
  -> [HttpSkipResponseCommand.cc:219] errorCode=3 Resource not found

04/20 18:06:38 [NOTICE] Download GID#f8aba5211bc76f35 not complete: 

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
f8aba5|ERR |       0B/s|https://github.com/dslackw/slpkg/archive/v3.3.5.tar.gz

Status Legend:
(ERR):error occurred.

aria2 will resume download if the transfer is restarted.
If there are any errors, then see the log file. See '-l' option in help/man page for details.

+==============================================================================
| Download 'v3.3.5.tar.gz' file [ FAILED ]
+==============================================================================

Would you like to continue [y/N]?

**Comment by dslackw** [comment]
Yes I had delay to release the version 3.3.5 but I have release the next version 3.3.6.
Everything works well now.
Thank you for the report!

**Comment by lupox** [comment]
Dear Dimitris Zlatanidis,

The email sent to lupox@lupox.tk with subject
"Re: [dslackw/slpkg] slpkg update slpkg "uri not found" (#108)"
will be delivered as soon as possible.

Your email address is automatically added to the
recipients 'whitelist'. This means for further
emails to lupox@lupox.tk, you will not receive a delivery
notification again.

TK MAILIAS
*************************************************
Looking for a way to Protect Your Identity and 
for a great no-more-spam solution for your email
address reply@reply.github.com? Sign up for TK Mailias.

It's free! Please visit http://www.mail.tk/
