### ISSUE TITLE
Download 'v3.3.6.tar.gz' file [ FAILED ] 

### ISSUE THREAD

**Issue by lupox** [dslackw/slpkg#109]
# /tmp/slpkg/build`//`slpkg-3.3.6.tar.gz

slpkg update slpkg

New version 'slpkg-3.3.6' is available !

Would you like to upgrade [y/N]? y

[1/1][ Download ] --> v3.3.6.tar.gz

04/22 02:30:17 [NOTICE] Downloading 1 item(s)

04/22 02:30:18 [NOTICE] CUID#7 - Redirecting to https://codeload.github.com/dslackw/slpkg/tar.gz/v3.3.6
[#33935f 0B/0B CN:1 DL:0B]                                                                                                                 
04/22 02:30:19 [NOTICE] Download complete: /tmp/slpkg/build//slpkg-3.3.6.tar.gz

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
33935f|OK  |   300KiB/s|/tmp/slpkg/build//slpkg-3.3.6.tar.gz

Status Legend:
(OK):download completed.

+==============================================================================
| Download 'v3.3.6.tar.gz' file [ FAILED ]
+==============================================================================

Would you like to continue [y/N]? y
Traceback (most recent call last):
  File "/usr/bin/slpkg", line 41, in <module>
    main()
  File "/usr/lib/python2.7/site-packages/slpkg/main.py", line 814, in main
    arguments[args[0]]()
  File "/usr/lib/python2.7/site-packages/slpkg/main.py", line 138, in command_update_slpkg
    it_self_update()
  File "/usr/lib/python2.7/site-packages/slpkg/slpkg_update.py", line 77, in it_self_update
    tar = tarfile.open(slpkg_tar_file)
  File "/usr/lib/python2.7/tarfile.py", line 1675, in open
    return func(name, "r", fileobj, **kwargs)
  File "/usr/lib/python2.7/tarfile.py", line 1740, in gzopen
    fileobj = gzip.GzipFile(name, mode, compresslevel, fileobj)
  File "/usr/lib/python2.7/gzip.py", line 94, in __init__
    fileobj = self.myfileobj = __builtin__.open(filename, mode or 'rb')
IOError: [Errno 2] No such file or directory: 'v3.3.6.tar.gz'

**Comment by lupox** [comment]
The system has several, aria2c, wget I guess aria2c.
The file is downloaded correctly but the program receives an error code.
Of all the forms in slackware 64bits does not give error only in 32bits.
I give it by resolved.

**Comment by lupox** [comment]
With wget works well with aria2c fails
1
DOWNDER=wget
DOWNDER_OPTIONS=-c -N

2
DOWNDER=aria2c
DOWNDER_OPTIONS=

**Comment by dslackw** [comment]
Yes I have fixed and it will be ready in the next release.
