### ISSUE TITLE
Parsing the $PKG.info REQUIRES line

### ISSUE THREAD

**Issue by bgrundy** [dslackw/slpkg#11]
This is basically a cut and paste from a report on another, similar SBo management tool:

Currently, slpkg reads the REQUIRES line of $PKG.info and attempts to install second depth dependencies FIRST, and then reverses the order of the REQUIRES line. In some cases, this results in either failed builds, or builds that may complete, but fail with errors during use. It would make more sense to have the REQUIRES line read in linear fashion, inserting and building dependencies as needed. This would give the SBo maintainer more control over the order of installation.

Real example: dfvfs (on SBo). From the REQUIRES line:

REQUIRES="construct protobuf libbde libewf libqcow libsmdev libsmraw libvhdi libvmdk libvshadow pytsk"

"slpkg -s sbo dfvfs" results in (built in this order):
sleuthkit pysetuptools six python-gflags python-dateutil pytz libvshadow libvmdk libvhdi libsmraw libsmdev libqcow libewf libbde protobuf construct dfvfs

This will break the installation because while libewf is optional for sleuthkit, the package we are installing (dfvfs) requires that sleuthkit be built with libewf support (and dfvfs is a dependency of plaso which requires the same).

if the package were build using the linear order of the REQUIRES line, it would look like this (secondary deps are in parentheses for illustration and are built immediately prior to their depending package):

Linear install queue: (six) construct (pysetuptools python-gflags python-dateutil pytz) protobuf libbde libewf libqcow libsmdev libsmraw libvhdi libvmdk libvshadow (sleuthkit) pytsk

With REQUIRES read linearly, the maintainer can specify that libewf should be installed prior to sleuthkit (for pytsk), and so sleuthkit is built with proper options for this package.  Pytsk is placed at the end so that it's dependancy, sleuthit, is built *after* libewf.  Providing the maintainer with the ability to explicitly direct the order of installation provides for more robust packaging.

**Comment by dslackw** [comment]
Ηι @bgrundy ,
I want to believe that it was understandable for me. What solution do you have ?? example, can change the user preferences tail ??

**Comment by bgrundy** [comment]
Solution would be to have slpkg install the packages in the same order as the REQUIRES specifies them, with each packages dependencies installed immediately before it.

So if REQUIRES for package A is "B  C  D" and package D requires Z, then the install queue would be:

B C Z D A 

Does that make sense?  Essentially, parse the REQUIRES line from front to back and add them to the queue in order written.  It is intuitive and provide greater control.

I'm sorry I don't know what "user preferences tail" means.

**Comment by dslackw** [comment]
Thank you understand exactly what you mean.
We will try to see if this could be done.

**Comment by dslackw** [comment]
Hi @bgrundy,
I think the solution was found in development version 2.2.2.
I did test and everything went well !

The installation order is:
http://asciinema.org/a/16288

**Comment by dslackw** [comment]
The solution was found by reversing the list instead of packages.
Before:
>>> packages = [['a'], ['b', 'c', 'd'], ['e']]
>>> packages = one_list(packages)
>>> packages
['a', 'b', 'c', 'd', 'e']
>>> packages.reverse()
>>> packages
['e', 'd', 'c', 'b', 'a']

The solution:
>>> packages = [['a'], ['b', 'c', 'd'], ['e']]
>>> packages.reverse()
[['e'], ['b', 'c', 'd'], ['a']]
>>> packages = one_list(packages)
['e', 'b', 'c', 'd', 'a']

This changes the first location list and then create a list...
What do you think is right;

**Comment by bgrundy** [comment]
Sorry for the delayed response.  

I'm not sure this solves the issue.  Looking at the output of your asciinema, it looks as though the order is still incorrect to capture the optional requirements that become hard requirements for a given package.  In the dfvfs example, it looks like sleuthkit is still installed before libewf.  The build will succeed, but the software will not perform as expected.

What is the purpose of the package.reverse() method? I can't tell what that accomplishes.  Particularly when the package in question becomes a nested requirement for another package.  Is the reverse even applied in that case?

Am I reading the output for slpkg in the asciinema correct?  Is sleuthkit installed first?  If so, than that is still not linear parsing.  sleuthkit should be installed immediately prior to pytsk.

[['six', 'construct'], ['pytz', 'python-dateutil', 'python-gflags', 'protobuf'], ['libbde'], ['libewf'], ['libqcow'], ['libsigscan'], ['libsmdev'], ['libsmraw'], ['libvhdi'], ['libvmdk'], ['libvshadow'], ['sleuthkit', 'pytsk']]

I apologize if I'm not being clear.  I'm not a programmer or a developer.  As it stands, in order to use this automated dependency resolution for the packages I maintain, it needs to be linear.

**Comment by dslackw** [comment]
The difference in version 2.2.2 is that it does not change the order has been placed by the maintainers of the package. 
Accomplish this by reversing the list and not the dependencies themselves.
But it can be installed optional packages listed in the README file should go in the file .info.

Could be done only if there was some way refer to the .info file like this:

REQUIRES = "six, pysetuptools, {libewf}"

but this is not as you know.
