### ISSUE TITLE
Upgrading with the "slack" repo wants to install almost 400 packages

### ISSUE THREAD

**Issue by Xylemon** [dslackw/slpkg#15]
When doing "slpkg -c slack --upgrade" it detects there's 21 packages to update, but also wants to install 396 packages as well. Why is this?

**Comment by dslackw** [comment]
What do you use 'stable' or 'current' ?? and version 14.1 ?

**Comment by Xylemon** [comment]
Sorry, I use "current", Slackware 14.1 64-bit, and slpkg 2.4.0

**Comment by dslackw** [comment]
Slackware 'current' is newly downloaded ? remember date ?

**Comment by Xylemon** [comment]
I'm not quite sure I follow.

**Comment by dslackw** [comment]
I could have a paste from your terminal here;

**Comment by Xylemon** [comment]
http://pastebin.com/cTtg7MyP

**Comment by dslackw** [comment]
Ok... and please '$ slpkg --help' paste

**Comment by Xylemon** [comment]
# slpkg --help            

slpkg - version 2.4.0 | Slackware release: current

**Comment by dslackw** [comment]
Indeed !! There no seems to be some issue with slpkg. The slpkg works with full Slackware distribution whenever you install each package you will not find on your system. This is because it can not work otherwise. Because some times new packages added to the distribution for smooth operation.

**Comment by Xylemon** [comment]
I am still not understanding why slpkg wants to install an additional 396 packages, isn't that command just supposed to update installed packages?

**Comment by dslackw** [comment]
Not when it comes to distribution upgrade I can not know what exactly needs a distribution to work properly. So slpkg trying to installed all packages missing from distribution.

**Comment by dslackw** [comment]
Recent example Patrick add many new packages how know if these packages is not dependencies in others packages or some package needed most? maybe the system crash.

**Comment by dslackw** [comment]
But because the user's freedom is what counts will try to give selection through configuration file /etc/slpkg/slpkg.conf . stay tuned...

**Comment by Xylemon** [comment]
Couldn't there be a command to update installed packages only versus upgrading by distribution?

**Comment by dslackw** [comment]
Because the command is included and works with all the repositories would be preferable to trouble with the other repositories. Find best option through the configuration file.

**Comment by Xylemon** [comment]
Why just not have the option to update packages from a repo of your choice? Like "slpkg -c slack --update" and it would only update installed packages?

**Comment by dslackw** [comment]
Beacuse option '--upgrade' make this work already for others repositories and such additional option perhaps confusing.

**Comment by Xylemon** [comment]
I don't think upgrade is useful for keeping updating packges if it makes me want to download over two gigs of nonsense.

**Comment by dslackw** [comment]
Yes but when the sound operation of a distribution available packages depend on others and not singularly packages that the user has installed.

**Comment by Xylemon** [comment]
So in short, there just can't be a simple option update what is already installed like every single other package manager ever?

**Comment by dslackw** [comment]
Yes has already been achieved in branch development and I believe a few hours to release version 2.4.1. The selection will be through the [/etc/slpkg/slpkg.conf](https://github.com/dslackw/slpkg/blob/develop/conf/slpkg.conf) configuration file (see variable ONLY_INSTALLED) and allows self just ask.

**Comment by Xylemon** [comment]
Ah ok I see now, that is exactly what I desired. Thank you for this, will close this issue now.

**Comment by dslackw** [comment]
I like to think is the best option for all users. Thank you for the debate and report.

**Comment by Xylemon** [comment]
It's no problem, also another question; would you ever consider an option that installs a package without dependency resolution? I find it useful at times when packages have un-needed dependencies.

**Comment by dslackw** [comment]
Yes, I had thought in the past. Maybe an option for this is to use '-q' option (queue). But I will try to see if there is a better choice.

**Comment by dslackw** [comment]
Version 2.4.1 was released. Option to upgrade only installed Slackware packages is available trough from configuration file such as turn on/off automatic resolve dependencies. But a additional option is available as you see in the '--help' section. Flag '--resolve-off' use instead edit configuration file to close automatic resolve dependencies. I believe to happy with this options but if find any isues please reporting me. Thank you.

**Comment by Xylemon** [comment]
Thank you for the additions!
