### ISSUE TITLE
The link the to the Changelog on the latest release is broken

### ISSUE THREAD

**Issue by Xylemon** [dslackw/slpkg#17]
On 2.5.0's release page, it links to: https://github.com/dslackw/slpkg/blob/master/CHANGELOG for the changelog. It should link to: https://github.com/dslackw/slpkg/blob/master/ChangeLog.txt

**Comment by dslackw** [comment]
Where is the link ?

**Comment by Xylemon** [comment]
https://github.com/dslackw/slpkg/releases

**Comment by dslackw** [comment]
Ohh i am sorry. I fix now ...
Thank you
