### ISSUE TITLE
Feature:  Parallel make flags (example MAKEFLAGS=${MAKEFLAGS:--j4}

### ISSUE THREAD

**Issue by BrentonEarl** [dslackw/slpkg#20]
I noticed that parallel make is not implemented in slpkg/pkg/build.py.  This feature is essential in speeding up compile times for packages from the Slackbuilds.org repository (sbo repo in slpkg).

_Please note:  I consider myself a novice python programmer at best.  I may have missed the fact that this feature already exists in the slpkg sources._

While I realize that sbopkg and slpkg are very different tools, this can be enabled in sbopkg.conf by adding:

export MAKEFLAGS=${MAKEFLAGS:--jX}

Where X in --jX equals the number of processor cores available on the host machine.

Taking it a step further, I think it would be best if slpkg could somehow determine the number of processor cores and set the MAKEFLAGS accordingly.  Some upstream sources (webkitgtk as an example) do not support setting MAKEFLAGS higher than -j1.  This feature would also need to somehow determine if the upstream source for each package being built, supports parallel make.

This is the one feature that is unavailable in slpkg that prevents me from completely switching over to slpkg as my primary package manager.

**Comment by dslackw** [comment]
I think you can work if you add it to "~./ bashrc" in the "/etc/profile" for all users.

**Comment by BrentonEarl** [comment]
I understand that I can export it as a bash variable prior to executing slpkg.  Setting it in /etc/profile or .bashrc are not sufficient for some sources because parallel make is not available for said sources.  As an example, if you compile webkitgtk with MAKEFLAGS set greater than -j1, it will error out.

What I am suggesting is that you add the ability for slpkg to automatically enable MAKEFLAGS based on the number of processors available.

I am also suggesting that slpkg is given the ability to determine if a source archive is compatible with parallel make.

These two features are not built into slackbuilds or sbopkg.  If slpkg had these features, I believe that it would be a real replacement for slackpkg and sbopkg.

**Comment by BrentonEarl** [comment]
Ok, I will do this instead.  I just thought there was some way for slpkg to automatically handle this for the user.

**Comment by websafe** [comment]
Maybe this should be placed in a FAQ or help or somewhere, because I was thinking about the same :-)

**Comment by dslackw** [comment]
I will not even close this issue because I am looking to find a solution that can output shell variable from Python script.

**Comment by BrentonEarl** [comment]
Some solution would be great.  Just adding the MAKEFLAGS to bashrc or /etc/profile seem incomplete as those are not even part of slpkg.

Maybe slpkg could read the number of processor cores from /proc/cpuinfo and set it's own MAKEFLAGS variable in memory just before a package is compiled?

**Comment by dslackw** [comment]
It is impossible to export environment variable from a child script. Another solution is "slpkg" auto edit sbo script to pass directly variable MAKEFLAGS but i don't like that solution.

**Comment by BrentonEarl** [comment]
I think you would run into other issues if you started having slpkg edit sbo scripts.  I wish I was more help, but I am a novice with python at best.  I usually only code in ruby.   Might be time to learn some python.

**Comment by dslackw** [comment]
This issue is not from Python. Just is difficult to export variable from a child processing.
When one script ends run all variables auto unset, so how can pass from one script to another (python to sbo script) ?

**Comment by dslackw** [comment]
I think solution found with python code os.environ["MAKEFLAGS"] = "-jX". See you soon  :+1:

**Comment by dslackw** [comment]
Solved in develop branch.
