### ISSUE TITLE
Would you like to continue [Y/n]?

### ISSUE THREAD

**Issue by websafe** [dslackw/slpkg#21]
And it's me again ;-) 

When I'm doing an upgrade `slpkg -c sbo --upgrade` or removal `-r`

I see:

`Would you like to continue [Y/n]?`

which I understand as: `Y` is the default (because it's a capital letter), so I only have to press enter to continue with the default. But it's not :-)

Then I'm thinking, maybe this capital `Y` means, a `y` won't be accepted as a `yes, please continue`? But no, when I enter a `y` the upgrade starts as I would type a capital `Y`...

**Comment by dslackw** [comment]
Thanks, must change to capital the letter "N" by default.

**Comment by dslackw** [comment]
Fixed in develop branch.

**Comment by websafe** [comment]
OK, great :+1:
