### ISSUE TITLE
Endless upgrade loop while updating chromium from alien repo

### ISSUE THREAD

**Issue by BrentonEarl** [dslackw/slpkg#22]
#### Software version
>  root@exitstatusone:~# slpkg -v
>  Version : 2.5.6

#### Summary

I upgraded chromium, chromium-pepperflash-plugin, and chromium-widevine-plugin from alien bob's repository and it looks like there is some issue sorting out which version of chromium-widevine-plugin to install.  I ran "slpkg -c alien --upgrade" 2 times now, and same results.

I have to go to work for an hour or two so I will take a closer look and report further when I return.

#### Output

>  +==============================================================================
| Total 4 packages installed and 2 packages upgraded
+==============================================================================
| Package chromium-widevine-plugin upgraded successfully
| Package chromium installed successfully
| Package chromium-pepperflash-plugin installed successfully
| Package chromium-widevine-plugin NOT installed
| Package chromium-widevine-plugin NOT installed
| Package chromium-widevine-plugin upgraded successfully
+==============================================================================
root@exitstatusone:~# slpkg -c alien --upgrade
Checking .....................................Done
Reading package lists ....Done
Resolving dependencies ...Done

>  The following packages will be automatically installed or upgraded 
with new version:

>  +==============================================================================
>  | Package                 New Version        Arch    Build  Repos          Size
>  +==============================================================================
>  Upgrading:
>    chromium-widevine-plugin-42.0.2311.135 42.0.2311.135      x86_64  1      alien        2228 K
>    chromium-widevine-plugin-42.0.2311.135 43.0.2357.130      x86_64  1      alien        2232 K
>  Installing for dependencies:
>    chromium-widevine-plugin-42.0.2311.135 42.0.2311.135      x86_64  1      alien        2228 K
>    chromium-43.0.2357.130  43.0.2357.130      x86_64  1      alien       59852 K
>    chromium-widevine-plugin-42.0.2311.135 43.0.2357.130      x86_64  1      alien        2232 K
>    chromium-pepperflash-plugin-18.0.0.194 18.0.0.194         x86_64  1      alien        4800 K

>  Installing summary
>  ===============================================================================
>  Total 6 packages.
>  0 package will be installed, 2 will be upgraded and 4 will be reinstalled.
>  Need to get 71.85 Mb of archives.
>  After this process, 262.06 Mb of additional disk space will be used.

>  Would you like to continue [y/N]?

**Comment by dslackw** [comment]
Yes and so to me, thank you for the reference will look immediately...

**Comment by dslackw** [comment]
It is alien repository issue, chromium packages double added.
http://www.slackware.com/~alien/slackbuilds/PACKAGES.TXT
But I will try to filter duplicate packages.

**Comment by BrentonEarl** [comment]
That would be excellent.  I am just thinking of how package manager resolve dependencies across multiple repositories in other Linux distributions.  Might be good to look for the newest version of a package in a repository, if at all possible.

**Comment by dslackw** [comment]
This normally should not be done. One package must be in the same name in PACKAGES.TXT. Now package "chromium-widevine-plugin" references two times.

**Comment by BrentonEarl** [comment]
The easiest solution would be to contact alien bob and have him remove the duplicates.

It may be a more permanent solution to sanitize the PACKAGES.TXT file for each repository in /var/lib/slpkg/<repo_dir>/ by removing duplicate entries.

**Comment by alienbob** [comment]
I do not see any issue on my side. Where are these double entries for the chromium-widevine-plugin package? I searched and could not find "chromium-widevine-plugin-42.0.2311.135 42.0.2311.135".in http://www.slackware.com/~alien/slackbuilds/PACKAGES.TXT at all.

Let me make clear that the file http://www.slackware.com/~alien/slackbuilds/PACKAGES.TXT contains the packages for my complete repository, for multiple Slackware releases and architectures. I don't know if that is the issue here? I am not familiar with slpkg.

Slackpkg in any case does not have any issue upgrading my chromium packages, and that is because in slackpkg I use a repository URL which is specific to the Slackware release and architecture I am running on my computer; in my case, the URL is http://taper.alienbase.nl/mirrors/people/alien/sbrepos/current/x86_64/ (fast mirror of http://www.slackware.com/~alien/sbrepos/current/x86_64/)

**Comment by dslackw** [comment]
Thank you Eric for the answer here.
Slpkg using the file PACKAGES.TXT to collect data. So in this file there are two versions of the same package 'chromium-widevine-plugin' '43 .0.2357.130 'and '42 .0.2311.135'.
I know your own file PACKAGES.TXT contains many versions but there is always one package with one version in each Slackware distribution and not see happening in the file 'chromium-widevine-plugin' which refers to two locations:
```
PACKAGE NAME:  chromium-widevine-plugin-43.0.2357.130-x86_64-1alien.txz
PACKAGE LOCATION:  ./chromium-widevine-plugin
PACKAGE SIZE (compressed):  2232 K
PACKAGE SIZE (uncompressed):  7790 K
PACKAGE REQUIRED:  chromium
PACKAGE CONFLICTS:  
PACKAGE SUGGESTS:  
PACKAGE DESCRIPTION:
chromium-widevine-plugin: chromium-widevine-plugin (Widevine plugin for Chromium)
chromium-widevine-plugin:
chromium-widevine-plugin: This package contains Google Chrome's Widevine DRM
chromium-widevine-plugin: plugin for Chromium (stable version).
chromium-widevine-plugin: Widevine Content Decryption Module enables Widevine
chromium-widevine-plugin: licenses for playback of HTML audio/video content.
chromium-widevine-plugin: The library is extracted from a Google Chrome RPM.
chromium-widevine-plugin: You will have to accept the bundled license file
chromium-widevine-plugin: if you want to use this closed-source plugin.
chromium-widevine-plugin:
chromium-widevine-plugin: chromium-widevine-plugin home: http://www.google.com/chrome
```
and

```
PACKAGE NAME:  chromium-widevine-plugin-42.0.2311.135-x86_64-1alien.txz
PACKAGE LOCATION:  ./slackbuilds
PACKAGE SIZE (compressed):  2228 K
PACKAGE SIZE (uncompressed):  7780 K
PACKAGE REQUIRED:  chromium
PACKAGE CONFLICTS:  
PACKAGE SUGGESTS:  
PACKAGE DESCRIPTION:
chromium-widevine-plugin: chromium-widevine-plugin (Widevine plugin for Chromium)
chromium-widevine-plugin:
chromium-widevine-plugin: This package contains Google Chrome's Widevine DRM
chromium-widevine-plugin: plugin for Chromium (stable version).
chromium-widevine-plugin: Widevine Content Decryption Module enables Widevine
chromium-widevine-plugin: licenses for playback of HTML audio/video content.
chromium-widevine-plugin: The library is extracted from a Google Chrome RPM.
chromium-widevine-plugin: You will have to accept the bundled license file
chromium-widevine-plugin: if you want to use this closed-source plugin.
chromium-widevine-plugin:
chromium-widevine-plugin: chromium-widevine-plugin home: http://www.google.com/chrome
```
If This is not a problem for you all right, I will do slpkg work a little differently about your own repository.

**Comment by BrentonEarl** [comment]
I've completely reinstalled slpkg from the most recent git version 2.5.6.  I deleted /var/log/slpkg, /etc/slpkg, /var/lib/slpkg as well, since removepkg did not properly clean up those files.

I think that if specific packages are selected by the user for installation, the newest version for those packages should be the only installation candidate.    This is how package managers work for many other distributions, so it was the assumed functionality.

1.  Slpkg finds all packages for all architectures when a search is ran for chromium.  I don't think slpkg should be looking for packages in other architectures unless I am running a multilib system.  My system is not multilib.
  * __Command 1:__ slpkg -F chromium
2.  Slpkg looks to find the correct dependencies for chromium and attempts to install the newest versions when running this command.  This looks to function correctly.
  * __Command 2:__ slpkg -s alien chromium
3.  I run into trouble when trying to install the three specific packages (pepperflash, widevine, chromium), rather than allowing slpkg to choose the packages for me.
  * __Command 3:__  slpkg -s alien chromium chromium-pepperflash-plugin chromium-widevine-plugin

#### Command no. 3

>  root@exitstatusone:~# slpkg -s alien chromium chromium-pepperflash-plugin chromium-widevine-plugin
>  Reading package lists ....Done
>  Resolving dependencies ....Done

>  The following packages will be automatically installed or upgraded 
with new version:

>  +==============================================================================
| Package                 New Version        Arch    Build  Repos          Size
+==============================================================================
Installing:
  chromium-widevine-plugin 42.0.2311.135      x86_64  1      alien        2228 K
  chromium-widevine-plugin 43.0.2357.130      x86_64  1      alien        2232 K
  chromium-pepperflash-plugin 18.0.0.194         x86_64  1      alien        4800 K
Installing for dependencies:
  chromium-widevine-plugin 42.0.2311.135      x86_64  1      alien        2228 K
  chromium                43.0.2357.130      x86_64  1      alien       59852 K
  chromium-widevine-plugin 43.0.2357.130      x86_64  1      alien        2232 K
  chromium-pepperflash-plugin 18.0.0.194         x86_64  1      alien        4800 K

>  Installing summary
>  ===============================================================================
Total 7 packages.
7 packages will be installed, 0 will be upgraded and 0 will be reinstalled.
Need to get 76.54 Mb of archives.
After this process, 278.77 Mb of additional disk space will be used.

>  Would you like to continue [y/N]? 

#### Command no. 1

>  root@exitstatusone:~# slpkg -F chromium

>  Packages with name matching [ chromium ]

>  +==============================================================================
| Repository  Package                                                      Size
+==============================================================================
  sbo         chromium-bsu-0.9.15.1                                         0 K
  sbo         chromium-31.0.1650.57                                         0 K
  alien       chromium-dev-pepperflash-plugin-18.0.0.114-i386-1alien.txz      4300 K
  alien       chromium-dev-pepperflash-plugin-18.0.0.114-x86_64-1alien.txz      4796 K
  alien       chromium-dev-widevine-plugin-45.0.2414.0-i386-1alien.txz      2292 K
  alien       chromium-dev-widevine-plugin-45.0.2414.0-x86_64-1alien.txz      2232 K
  alien       chromium-dev-45.0.2414.0-i486-1alien.txz                  55688 K
  alien       chromium-dev-45.0.2414.0-x86_64-1alien.txz                60880 K
  alien       chromium-pepperflash-plugin-18.0.0.194-i386-1alien.txz      4304 K
  alien       chromium-pepperflash-plugin-18.0.0.194-i386-1alien.txz      4304 K
  alien       chromium-pepperflash-plugin-18.0.0.194-x86_64-1alien.txz      4800 K
  alien       chromium-pepperflash-plugin-18.0.0.194-x86_64-1alien.txz      4800 K
  alien       chromium-widevine-plugin-43.0.2357.130-i386-1alien.txz      2292 K
  alien       chromium-widevine-plugin-43.0.2357.130-i386-1alien.txz      2292 K
  alien       chromium-widevine-plugin-43.0.2357.130-x86_64-1alien.txz      2232 K
  alien       chromium-widevine-plugin-43.0.2357.130-x86_64-1alien.txz      2232 K
  alien       chromium-37.0.2062.94-i486-1alien.txz                     44188 K
  alien       chromium-37.0.2062.94-i486-1alien.txz                     44188 K
  alien       chromium-43.0.2357.130-i486-1alien.txz                    53712 K
  alien       chromium-43.0.2357.130-i486-1alien.txz                    53712 K
  alien       chromium-37.0.2062.94-x86_64-1alien.txz                   43524 K
  alien       chromium-37.0.2062.94-x86_64-1alien.txz                   43524 K
  alien       chromium-43.0.2357.130-x86_64-1alien.txz                  59852 K
  alien       chromium-43.0.2357.130-x86_64-1alien.txz                  59852 K
  alien       chromium-widevine-plugin-42.0.2311.135-i386-1alien.txz      2284 K
  alien       chromium-widevine-plugin-42.0.2311.135-i386-1alien.txz      2284 K
  alien       chromium-widevine-plugin-42.0.2311.135-x86_64-1alien.txz      2228 K
  alien       chromium-widevine-plugin-42.0.2311.135-x86_64-1alien.txz      2228 K

>  Found summary
>  ===============================================================================
>  Total found 28 packages in 2 repositories.

**Comment by dslackw** [comment]
Yes options '--FIND' and '--list' do not filter per release distribution packages. 
It is only for information but will fix.

**Comment by dslackw** [comment]
As there is no problem with the other packages, like:

```
root@darkstar /h/d/s/slpkg# slpkg -s alien atkmm
Reading package lists ....Done
Resolving dependencies ...Done

The following packages will be automatically installed or upgraded 
with new version:

+==============================================================================
| Package                 New Version        Arch    Build  Repos          Size
+==============================================================================
Installing:
  atkmm                   2.22.6             x86_64  1      alien         124 K
Installing for dependencies:
  libsigc++               2.2.10             x86_64  2      alien         128 K
  glibmm                  2.32.1             x86_64  1      alien        1012 K
  cairomm                 1.10.0             x86_64  2      alien         124 K
  pangomm                 2.28.4             x86_64  1      alien         124 K

Installing summary
===============================================================================
Total 5 packages.
5 packages will be installed, 0 will be upgraded and 0 will be reinstalled.
Need to get 1.48 Mb of archives.
After this process, 7.85 Mb of additional disk space will be used.

Would you like to continue [y/N]?
```

**Comment by BrentonEarl** [comment]
@dslackw  You may have already done this search.  But it looks there are duplicate entries in PACKAGES.TXT on my system.  Running a diff on alienbob's remote PACKAGES.TXT against this file found no differences.

Comparing the results and actually physically checking what is in the repository (http://www.slackware.com/~alien/slackbuilds/pkg/current/), there aren't any duplicate packages.  If you look at the output listed in my previous post under heading __Command no. 3__, you will see that slpkg is attempting to install packages from current on my stable system.

Here is a screenshot of the original output:  http://bit.ly/1HkU37g

#### On my system

>  File: /var/lib/slpkg/alien_repo/PACKAGES.TXT
>  
>  Line 3903
>  PACKAGE NAME:  chromium-widevine-plugin-43.0.2357.130-i386-1alien.txz
>  PACKAGE LOCATION:  ./chromium-widevine-plugin/pkg/14.1
>  
>  Line 3923
>  PACKAGE NAME:  chromium-widevine-plugin-43.0.2357.130-i386-1alien.txz
>  PACKAGE LOCATION:  ./chromium-widevine-plugin/pkg/current
>  
>  Line 3943
>  PACKAGE NAME:  chromium-widevine-plugin-43.0.2357.130-x86_64-1alien.txz
>  PACKAGE LOCATION:  ./chromium-widevine-plugin/pkg64/14.1
>  
>  Line 3963
>  PACKAGE NAME:  chromium-widevine-plugin-42.0.2311.135-i386-1alien.txz
>  PACKAGE LOCATION:  ./pkg/14.1
>  
>  Line 45035
>  PACKAGE NAME:  chromium-widevine-plugin-42.0.2311.135-i386-1alien.txz
>  PACKAGE LOCATION:  ./pkg/current
>  
>  Line 45055
>  PACKAGE NAME:  chromium-widevine-plugin-42.0.2311.135-i386-1alien.txz
>  PACKAGE LOCATION:  ./pkg/current
>  
>  Line 45075
>  PACKAGE NAME:  chromium-widevine-plugin-42.0.2311.135-x86_64-1alien.txz
>  PACKAGE LOCATION:  ./pkg64/14.1
>  
>  Line 45095
>  PACKAGE NAME:  chromium-widevine-plugin-42.0.2311.135-x86_64-1alien.txz
>  PACKAGE LOCATION:  ./pkg64/current

#### Duplicates

>  sort /tmp/widvine-plugin.txt | uniq -d
>  
> PACKAGE LOCATION:  ./pkg/current
> PACKAGE NAME:  chromium-widevine-plugin-42.0.2311.135-i386-1alien.txz
> PACKAGE NAME:  chromium-widevine-plugin-42.0.2311.135-x86_64-1alien.txz
> PACKAGE NAME:  chromium-widevine-plugin-43.0.2357.130-i386-1alien.txz

**Comment by dslackw** [comment]
This issue fix in develop branch. I changed mirror.

**Comment by dslackw** [comment]
This issue fixed in develop branch. 
Thanks @BrentonEarl for reference and Thanks @alienbob for mirrors share and fast answer.

**Comment by dslackw** [comment]
Slpkg v2.5.7 released.
@BrentonEarl if everything is working properly like me please close this topic.
Thanks.

**Comment by BrentonEarl** [comment]
On my way home from a baseball game .  I will update slpkg and check when I get home in about a half hour.

**Comment by BrentonEarl** [comment]
All good.  Thanks for your hard work @dslackw .
