### ISSUE TITLE
Cannot verify md5 checksums from "alien" repository

### ISSUE THREAD

**Issue by BrentonEarl** [dslackw/slpkg#23]
#### Summary

_This is with a fresh install of slpkg from github version 2.5.7_

This is an issue that stems off of issue #22 .  When installing packages from alien bob's repository, md5 check sums cannot be verified.  The md5sums are not found by slpkg/slpkg/grep_md5.py.

It's this bit of code right here in grep_md5.py starting on line 47, I think:
```python
    if repo == "alien":
        end = ""
    for line in CHECKSUMS_md5.splitlines():
        if line.endswith("%s%s" % (end, binary)):
            md5 = line.split()[0]
```

#### Reproduced by

>  slpkg -s alien vlc
>  slpkg -s alien chromium
_etc._

#### Output

>  root@exitstatusone:~# slpkg -s alien vlc
>  Reading package lists ....Done
>  Resolving dependencies ...Done

>  The following packages will be automatically installed or upgraded 
with new version:

>  +==============================================================================
| Package                 New Version        Arch    Build  Repos          Size
+==============================================================================
Installing:
  vlc                     2.2.1              x86_64  1      alien       33864 K

>  Installing summary
>  ===============================================================================
Total 1 package.
1 package will be installed, 0 will be upgraded and 0 will be reinstalled.
Need to get 33.07 Mb of archives.
After this process, 124.28 Mb of additional disk space will be used.

>  Would you like to continue [y/N]? y

>  [1/1][ Download ] --> vlc-2.2.1-x86_64-1alien.txz

>  --2015-06-27 23:55:04--  http://taper.alienbase.nl/mirrors/people/alien/sbrepos/14.1/x86_64/vlc/vlc-2.2.1-x86_64-1alien.txz
>  Resolving taper.alienbase.nl (taper.alienbase.nl)... 98.158.153.254
>  Connecting to taper.alienbase.nl (taper.alienbase.nl)|98.158.153.254|:80... connected.
>  HTTP request sent, awaiting response... 416 Requested Range Not Satisfiable

>      The file is already fully retrieved; nothing to do.

>  +==============================================================================
| MD5SUM check for vlc-2.2.1-x86_64-1alien.txz [ FAILED ]
>  +==============================================================================
| Expected: 909008a41d406ad1f4206a468e00a3f0
| Found: None
>  +==============================================================================

>  Would you like to continue [y/N]? N

**Comment by dslackw** [comment]
Sorry about this, after changing mirror forgot to configure the specifics repository alien.
Fixed in develop branch.

**Comment by BrentonEarl** [comment]
Ok no problem.  I will test on "develop" branch for now on.

**Comment by dslackw** [comment]
Also you can try version 2.5.8

**Comment by BrentonEarl** [comment]
Verified fixed.
