### ISSUE TITLE
Alien repository - wrong packages

### ISSUE THREAD

**Issue by lucashpandolfo** [dslackw/slpkg#24]
At latest version (2.5.8).

slpkg.conf has `RELEASE=current`, and the alien repository enabled.

`slpkg -F libreoffice` returns the `libreoffice 4.4.1` packages (http://www.slackware.com/~alien/slackbuilds/libreoffice/pkg64/14.1/), which is wrong, since `current` repo has `libreoffice 4.4.3`.

Downgraded to `slpkg 2.5.6` (i had the txz), then after a `slpkg upgrade`, the correct packages were found.

**Comment by dslackw** [comment]
Please upgrade package lists with command '# slpkg upgrade' and try again.

**Comment by dslackw** [comment]
Yes, because version 2.5.8 use new mirror for alien repository, need upgrade to remove old and replace with new.

**Comment by lucashpandolfo** [comment]
Even if i do `slpkg upgrade`, still `libreoffice 4.4.1` is found instead of 4.4.3.

**Comment by dslackw** [comment]
If you changed version in -current should again update the lists packages with the command 'slpkg update', but then you used packages only for version -current.

**Comment by lucashpandolfo** [comment]
I don't understand what you mean.

I'm in current. Now, here is the thing.

In `slpkg/slack/slack_version.py`, you define `slack_ver` reading from `/etc/slackware-version`.
Even on `current`, the version is `14.1` (it is not updated until the next slackware release).
Now, if i change the version in said file to `current`, everything breaks, as `slack_version` is expected to be a number ``(".".join(re.findall(r"\d+", sv)))``

**Comment by lucashpandolfo** [comment]
If i just force `slack_version` to `"current"`, then alien repository works fine (`libreoffice 4.4.3` at last), but then `sbo` repo stops working (as `slackbuilds` has a `14.1` repo but not a `current` repo).

**Comment by dslackw** [comment]
Each time changed variable RELEASE, after must run 'slpkg update' to update package lists. Have you done that ?

**Comment by lucashpandolfo** [comment]
Yes, i have.

```bash
root@Sigma:~# grep "\(REL\)\|\(REPO\)" /etc/slpkg/slpkg.conf
RELEASE=current
# Choose repositories want to work. Read first REPOSITORIES file.
REPOSITORIES=slack,sbo,alien
root@Sigma:~# cat /etc/slackware-version 
Slackware 14.1
root@Sigma:~# slpkg upgrade

Check and update repositories:

Update repository slack ....................................................Done
Update repository sbo ....................................................................................................Done
Update repository alien ............................Done
root@Sigma:~# slpkg -F libreoffice | grep alien
  alien       libreoffice-4.4.1-x86_64-1alien.txz                      114856 K
  alien       libreoffice-dict-af-4.4.1-x86_64-1alien.txz                 516 K
  alien       libreoffice-dict-ar-4.4.1-x86_64-1alien.txz                1164 K
  alien       libreoffice-dict-be-4.4.1-x86_64-1alien.txz                 280 K
# etc ..

root@Sigma:~# echo Slackware current > /etc/slackware-version 
root@Sigma:~# slpkg upgrade

Check and update repositories:

Update repository slack ....................................................Done
Update repository sbo ...
Can't read file 'SLACKBUILDS.TXT'

Can't read file 'ChangeLog.txt'

Can't read file 'SLACKBUILDS.TXT'

Can't read file 'ChangeLog.txt'
Done
Update repository alien ...
Can't read file 'PACKAGES.TXT'

Can't read file 'CHECKSUMS.md5'
............Done
root@Sigma:~# slpkg -F libreoffice             

Packages with name matching [ libreoffice ]

+==============================================================================
| Repository  Package                                                      Size
+==============================================================================

Found summary
===============================================================================
Total found 0 packages in 0 repositories.

root@Sigma:~# echo Slackware 14.1 >  /etc/slackware-version
root@Sigma:~# sed 's/return.*/return "current"/' -i /usr/lib64/python2.7/site-packages/slpkg/slack/slack_version.py
root@Sigma:~# slpkg upgrade

Check and update repositories:

Update repository slack ....................................................Done
Update repository sbo ...
Can't read file 'SLACKBUILDS.TXT'

Can't read file 'ChangeLog.txt'

Can't read file 'SLACKBUILDS.TXT'

Can't read file 'ChangeLog.txt'
Done
Update repository alien ...........................Done

root@Sigma:~# slpkg -F libreoffice | grep alien
  alien       libreoffice-4.4.3-x86_64-1alien.txz                      114168 K
  alien       libreoffice-dict-af-4.4.3-x86_64-1alien.txz                 516 K
  alien       libreoffice-dict-ar-4.4.3-x86_64-1alien.txz                1164 K
  alien       libreoffice-dict-be-4.4.3-x86_64-1alien.txz                 280 K
  alien       libreoffice-dict-bg-4.4.3-x86_64-1alien.txz                 904 K

#... etc
```

**Comment by BrentonEarl** [comment]
Changing /etc/slackware-version should have no effect on slpkg.

**Comment by BrentonEarl** [comment]
I am installing a slackware64 14.1 vm right now and about to test a 14.1 to -current upgrade to see what exactly he is talking about.

**Comment by BrentonEarl** [comment]
The libreoffice version that is in alien bob's repository is 4.4.3 (http://taper.alienbase.nl/mirrors/people/alien/sbrepos/current/x86_64/libreoffice/)

This is after updating to slpkg 2.5.8.  I've also updated the base system with slpkg -s slack --upgrade.

I've verified that on a fresh install of Slackware64 14.1 that after the RELEASE variable is changed to 'current' in /etc/slpkg/slpkg.conf, 'slpkg -s alien libreoffice' shows the following:

>  root@slack-current-test:~/slpkg-2.5.8# slpkg -s alien libreoffice
>  Reading package lists ....Done
>  Resolving dependencies ...Done
>  
>  The following packages will be automatically installed or upgraded 
with new version:
>  
>  +==============================================================================
| Package                 New Version        Arch    Build  Repos          Size
+==============================================================================
Installing:
  libreoffice             4.4.1              x86_64  1      alien      114856 K

>  Installing summary
>  ===============================================================================
>  Total 1 package.
>  1 package will be installed, 0 will be upgraded and 0 will be reinstalled.
>  Need to get 112.16 Mb of archives.
>  After this process, 574.19 Mb of additional disk space will be used.
>  
>  Would you like to continue [y/N]? N
root@slack-current-test:~/slpkg-2.5.8#

**Comment by dslackw** [comment]
Fixed in develop branch.
Thanks for reporting.

**Comment by lucashpandolfo** [comment]
Thanks for the fast fix.
