### ISSUE TITLE
Removing the terminal emulator "st" shows wrong dependency

### ISSUE THREAD

**Issue by BrentonEarl** [dslackw/slpkg#26]
#### Summary 
While attempting to remove the terminal emulator "st" from SBo, slpkg states that "perl-www-mechanize" SBo package needs to be removed as a dependency.  I maintain "perl-www-mechanize" and "st" is not a dependency of this package, and "perl-www-mechanize" is not a dependency of "st".

>  root@exitstatusone:~# slpkg -v
>  Version : 2.5.9
>  root@exitstatusone:~# cat /etc/slackware-version 
>  Slackware 14.1

#### Relevant Files

_perl-www-mechanize.info file:_
*  https://github.com/BrentonEarl/es1-slackware-stuff/blob/master/slackbuilds/perl/perl-www-mechanize/perl-www-mechanize.info

_st.info file:_
*  https://github.com/willysr/slackbuilds/blob/sbo/system/st/st.info

#### Output
>  root@exitstatusone:~# slpkg -t sbo st
>  Resolving dependencies ...Done
>  
>  +==========================
>  | Package st dependencies :
>  +==========================
>  \
>   +---[ Tree of dependencies ]
>   |
>   +--1: No dependencies

>  root@exitstatusone:~# slpkg -r st --check-deps

>  Packages with name matching [ st ]

>  [ delete ] --> st-0.4.1-x86_64-1_SBo

>  Are you sure to remove 1 package [y/N]? y

>  +=============================================================================
|                               !!! WARNING !!!
+=============================================================================
| st is dependency of the package --> perl-www-mechanize
+==============================================================================
+=============================================================================
| Insert packages to exception removal:
+=============================================================================
 >

**Comment by dslackw** [comment]
Please paste result from:
```
cat /var/log/slpkg/dep/perl-www-mechanize
```

**Comment by BrentonEarl** [comment]
```bash
root@exitstatusone:~# cat /var/log/slpkg/dep/perl-www-mechanize
perl-Sub-Uplevel
perl-tree-dagnode
perl-html-tagset
perl-encode-locale
perl-html-parser
perl-http-date
perl-lwp-mediatypes
perl-IO-HTML
perl-http-message
perl-file-listing
perl-http-cookies
perl-http-daemon
perl-http-negotiate
perl-net-http
perl-www-robotrules
libwww-perl
perl-html-form
perl-http-response-encoding
perl-http-server-simple
perl-test-warn

**Comment by BrentonEarl** [comment]
I do not have perl-www-mechanize installed right now either.

**Comment by dslackw** [comment]
Okay, we found the problem and will be solved in the next few hours I believe.

**Comment by dslackw** [comment]
Fixed in develop branch.
Many Thanks Brenton Earl.

**Comment by BrentonEarl** [comment]
No problem.  As always, thanks for the quick responses.
