### ISSUE TITLE
Multilib, how is it handled by slpkg?

### ISSUE THREAD

**Issue by BrentonEarl** [dslackw/slpkg#27]
I recently switched my 14.1 system to a multilib installation again.  I am having a difficult time finding documentation about how to tell slpkg that my system is multilib.

What is the process to do this?

I would rather not black list all multilib packages and have slpkg handle updates for all packages on my system.

**Comment by dslackw** [comment]
```
$ slpkg -c slack --upgrade --skip="multi:*multilib*
```
There are reports in the file README.rst otherwise read man page.

**Comment by dslackw** [comment]
Everything is alright Brenton ?

**Comment by BrentonEarl** [comment]
Yes, sorry.  I went to sleep and forgot to respond.   Everything looks good on my end.
