### ISSUE TITLE
[OT] Strange situation in Slackware64 14.1 patches 

### ISSUE THREAD

**Issue by websafe** [dslackw/slpkg#31]
I've discovered something strange in the official repository of Slackware64 14.1
and described it here http://www.linuxquestions.org/questions/slackware-14/slackware64-14-1-strange-build-number-in-patches-4175548570/ and here https://www.facebook.com/groups/LinuxSlackware/permalink/10153480171093205/

How will `slpkg` react in this case?

Pasting it below:

Hmm, maybe it's because I'm tired, but I've found something strange? If you take a look at http://sunsite.icm.edu.pl/pub/Linux/slackware/slackware64-14.1/slackware64/a/ You'll find there the following kernel packages:

 + kernel-generic-3.10.17-x86_64-3.txz
 + kernel-huge-3.10.17-x86_64-3.txz
 + kernel-modules-3.10.17-x86_64-3.txz

As you can see, all packages are v. 3.10.17 and BUILD 3 (three), created on 23-Oct-2013. That's OK, but why the hell is a newer (14-Feb-2014!) BUILD 2 (two) in patches?!?

http://sunsite.icm.edu.pl/pub/Linux/slackware/slackware64-14.1/patches/packages/linux-3.10.17-2/

 + kernel-generic-3.10.17-x86_64-2.txz
 + kernel-huge-3.10.17-x86_64-2.txz
 + kernel-modules-3.10.17-x86_64-2.txz

Why is build 2 (and not 4) in patches?

**Comment by dslackw** [comment]
Slpkg download patches and then run Slackware command ```upgradepkg --install-new``` to apply patches. Maybe Patrick decided to do script downgrade.

**Comment by websafe** [comment]
OK @dslackw. But this situation still looks strange. Robby Workman will take a look at this. I've e-mailed him [as he asked on FB](https://www.facebook.com/groups/LinuxSlackware/permalink/10153480171093205/?comment_id=10153480227783205&offset=0&total_comments=3&comment_tracking={%22tn%22%3A%22R0%22}).

**Comment by dslackw** [comment]
Chances are it has corrected the script or the build number. I believe the Robby will give an answer.

**Comment by BrentonEarl** [comment]
I don't spend a lot of time on facebook.  When you get an answer, could you guys please post it back here?

**Comment by websafe** [comment]
Sure :+1: I will.

**Comment by websafe** [comment]
Robby Workman explained on Facebook what happened in 14.1 /patches:
> **Robby Workman** Ohhhh, that was accidental, but the ones in /patches are newer and what you should have installed. Pat's take on it was "oops - but people should be upgrading to what's in /patches and upgradepkg will do the right thing so oh well"

There's also an explanation in the [LinuxQuestions thread](http://www.linuxquestions.org/questions/slackware-14/slackware64-14-1-strange-build-number-in-patches-4175548570/#post5394783)

> **allend** Welcome to the club.
> http://www.linuxquestions.org/questions/slackware-14/slackware%27s-kernel-mystery-4175504331/
> http://www.linuxquestions.org/questions/slackware-14/version-number-confusion-4175520633/
> http://www.linuxquestions.org/questions/slackware-14/slackware64-14-1-kernel-build-numbers-4175530380/
> Essentially it was a small error that occurred when quickly addressing a nasty kernel bug.

**Comment by BrentonEarl** [comment]
Thanks.
