### ISSUE TITLE
Wrong Multilib repository

### ISSUE THREAD

**Issue by lucashpandolfo** [dslackw/slpkg#32]
Something like #24

Slpkg uses the version in `/etc/slackware-version`, completely ignoring the `RELEASE=current` variable in the config and retrieves `http://www.slackware.com/~alien/multilib/14.1/PACKAGES.TXT` instead of `http://www.slackware.com/~alien/multilib/current/PACKAGES.TXT`

```bash
bash-4.3# cat /etc/slackware-version 
Slackware 14.1
bash-4.3# cat /etc/slpkg/slpkg.conf | grep RELEASE
RELEASE=current
bash-4.3# slpkg upgrade

Check and update repositories:

Check repository [multi] ... 
[1/1][ Download ] --> PACKAGES.TXT

--2015-07-27 11:12:47--  http://www.slackware.com/~alien/multilib/14.1/PACKAGES.TXT
```

**Comment by dslackw** [comment]
Thanks for report. Typo is problem [typo](https://github.com/dslackw/slpkg/blob/master/slpkg/init.py#L398)
