### ISSUE TITLE
Issues with updating all packages (especially on a new system)

### ISSUE THREAD

**Issue by Xylemon** [dslackw/slpkg#33]
I love how with slpkg, I can upgrade packages I have installed only. It provides an experience similar to slapt-get and so on. However, there are some odd issues when working with the slack repo. For instance, I installed Slackware 14.1 on a new system today, removed the packages I didn't desire, upgraded kernel, rebooted,installed slpkg, and tweaked it to use current packages. I experienced an annoying trait of slpkg (this also happened with slapt-get when I used it a while back) that some critical packages like evdev and libsxhmfence are removed when upgrading all your packages for no apparent reason. Another awful issue is it's impossible to upgrade nouveau correctly due to it always thinking the blacklist package is an upgrade, perhaps the blacklist package should be ignored by default? The last crucial problem is that for whatever reason, it seems slpkg didn't update every program! So some important packages like the glibc series were outdated and barely anything ran! Could any insight be provided as to why this happened or any fixes be brought forth? Upgrading all your packages can be a deadly experience!

Specs: Slackware Linux 14.1 64-bit with kernel 3.18.11 and slpkg 2.6.8

**Comment by BrentonEarl** [comment]
Without knowing the packages that showed up in the list that slpkg shows after you type "slpkg -c slack --upgrade "  , telling you what went wrong and fixing any bugs will be a difficult task.

Some immediate questions I thought of after reading your post are:

What repository did you use to upgrade?

Have you compared the installed packages on your system to the available packages on your remote mirror? 

Are you mixing -current with 14.1?  slpkg does not officially support -current branch of Slackware.

**Comment by dslackw** [comment]
Have you tried change variable ONLY_INSTALLED in "on" to the /etc/slpkg/slpkg.conf file ?

**Comment by dslackw** [comment]
@BrentonEarl slpkg support -current branch.

**Comment by BrentonEarl** [comment]
I thought I read in the docs that it didn't have support?

**Comment by BrentonEarl** [comment]
https://github.com/dslackw/slpkg/blob/master/REPOSITORIES

Top of that file says it doesn't.

**Comment by Xylemon** [comment]
@BrentonEarl I used the "slack" repo with one of the kernel.org mirrors. I have been comparing the packages to my other system and researching missing libraries to find any missing packages

@dslackw Yes I did do that.

However after reading these comments, I believe I am doing something incredibly stupid. I knew that the "current" packages were updated packages that eventually make it into the next release of Slackware, but I also noticed there is a "current" ISO, so I'm assuming this is why I'm having so many issues. If I understand this correctly, the "current" setting of slpkg's configuration is really meant for the current ISO release of Slackware, and the "stable" setting is meant for 14.1 users, correct?

**Comment by dslackw** [comment]
Yes this might confuse, but referred to the repository SBo.

**Comment by dslackw** [comment]
@Xylemon Yes, the -current branch compare all packages from ISO and -stable compare only patches.

**Comment by Xylemon** [comment]
So is using the "current" setting on a 14.1 system heavily advised? Because I've done this before and have only had one or two minor problems. 

Also, it seems that turning off "only-installed" gave me a list of packages I didn't have installed (because I uninstalled them during setup) but also listed the packages that were still outdated (like make) and ready to b e upgraded. Why does "only installed" not detect these outdated packages?

**Comment by dslackw** [comment]
When try upgrade distribution with "ONLY_INSTALLED" is off slpkg check any packages missing from installed distribution by default. If "ONLY_INSTALLED" is "on" slpkg check any installed packages is minimum by version and build from mirror packages.

**Comment by Xylemon** [comment]
Right, but I was saying there were packages i had installed that weren't detected for an upgrade when only installed was set on. I had to turn it off in order to see what was still outdated.

**Comment by dslackw** [comment]
This sounds strange.I should know the steps followed before it and what were the packages ?

**Comment by dslackw** [comment]
And even two differences, if ONLY_INSTALLED is "on" slpkg use local PACKAGES,TXT before it update with command "slpkg update" and if ONLY_INSTALLED is "off" use remote PACKAGES.TXT from mirror server.

**Comment by Xylemon** [comment]
On Slackware 14.1, I configured slpkg to use "current" packages, and to update only installed. I also used  a mirror since the main site isn't always updated. Did upgrade/update then entered "slpkg -c slack --upgrade". It upgraded many packages, but quite a few were left out. Here's a list:

all glibc packages
xscreensaver
bc binutis
boost
make
qt
udisks
util-linux
sdl
make
vte
wget
man
mkinitrd
gvfs
some Xorg related packages
and there is more. I turned "only installed" off and was able to write down the rest and upgrade them.

**Comment by dslackw** [comment]
Any ago updated list of packages with the command "slpkg update"?

**Comment by dslackw** [comment]
Check packages in /var/lib/slpkg/slack_repo/

**Comment by dslackw** [comment]
Meaning that you have installed the version Slackware 14.1 -stable and used packages from -current branch ?

**Comment by Xylemon** [comment]
I still have udisks outdated. I turned on "only installed" and ran "slpkg update". Afterwords I ran "slpkg -c slack --upgrade" to which slpkg spat out "Not found packages for upgrade" even though when "only installed" is off it detects udisks needs to be updated.

And yes, I installed Slackware 14.1 -stable and configured slpkg to use current packages.

**Comment by dslackw** [comment]
"And yes, I installed Slackware 14.1 -stable and configured slpkg to use current packages."

Slpkg checks for packages with the same name that are installed in your distribution with packages available in the repository If ONLY_INSTALLED is "on". No matter from what repository installed.

**Comment by dslackw** [comment]
So ONLY_INSTALLED is "on", include packages when installed with distribution.

**Comment by dslackw** [comment]
@Xylemon you understand;

**Comment by Xylemon** [comment]
@dslackw I believe so. I'm also very busy with some other things, so I'll close this for now.
