### ISSUE TITLE
Slackware ARM 14.1 - Cannot upgrade with slpkg

### ISSUE THREAD

**Issue by BrentonEarl** [dslackw/slpkg#36]
### Problem
When I try to upgrade my raspberry pi, slpkg does not see updates that I know are available.  In addition, it takes several minutes for slpkg to return output after running "slpkg -c slarm --upgrade".  
I've added the main Slackware ARM mirror as a custom repository since it was not available in slpkg by default.

I believe the issue is that slpkg doesn't know how to parse the files on these mirrors because they are a different structure than slpkg expects to parse.

"slackpkg upgrade-all" works just fine.  I have ruled out issues with the mirrors.

Repository -   ftp://ftp.arm.slackware.com/slackwarearm/slackwarearm-14.1/
Slpkg version - 2.7.1
Slackware release - 14.1 ARM

### Changelog
```bash
Sat Aug  8 11:22:33 UTC 2015
patches/packages/ca-certificates-20150426-noarch-1_slack14.1.txz:  Upgraded.
  This package updates to the latest CA certificates.
patches/packages/mozilla-nss-3.19.2-arm-1_slack14.1.txz:  Upgraded.
  This release contains security fixes and improvements.
  For more information, see:
    http://www.mozilla.org/security/known-vulnerabilities/nss.html
  (* Security fix *)
+--------------------------+
```

### Slpkg output

```bash
facerip@raspi:/tmp$ su -c "slpkg -c slarm --upgrade"
Password:
Checking... Done
Reading package lists... Done
Resolving dependencies... Done

Not found packages for upgrade
```

### Additional ARM Mirrors  ( _14.0, 14.1, -current_ )
ftp://ftp.arm.slackware.com/slackwarearm/
ftp://ftp.slackware.pl/pub/slackwarearm/
ftp://mirror.inode.at/slackwarearm/
ftp://mirrors.vbi.vt.edu/linux/slackwarearm/
ftp://ftp.halifax.rwth-aachen.de/slackwarearm/
ftp://mirrors-usa.go-parts.com/slackware/
ftp://mirrors-ru.go-parts.com/slackware/
ftp://mirrors-au.go-parts.com/slackware/
ftp://mirrors-br.go-parts.com/slackware/

**Comment by dslackw** [comment]
Yes you are right. There is a peculiarity in the patches folder and slpkg can't check custom repository so should the Slackware arm to pass the default repositories. So i will try pass arm repository like -stable and -currrent.

**Comment by dslackw** [comment]
So, you can give me result from arm system:
```
$ uname -m
```

**Comment by dslackw** [comment]
Is "arm" i suppose

**Comment by dslackw** [comment]
Fixed in develop branch but i can't tested from me if working. i don't have arm systme now.

**Comment by BrentonEarl** [comment]
I will test it tomorrow.  I was busy with family most of today.

**Comment by dslackw** [comment]
Thanks, take your time :+1:

**Comment by BrentonEarl** [comment]
I have the develop branch cloned onto my arm device.  I am not sure how to build a package from the develop branch.  I would like to avoid using install.sh because it looks like it doesn't leave a way to remove the created files after I am finished testing.  How can I build a package from the develop branch?
```bash
facerip@raspi:~/USB/Projects/slpkg$ uname -m 
armv6l
```
I have access to just the Raspberry Pi B+ and have no other arm devices.

**Comment by dslackw** [comment]
Try after clone:

```
$ mv slpkg slpkg-2.7.1
$ tar zcvf slpkg-2.7.1.tar.gz slpkg-2.7.1
$ cd slpkg-2.7.1
$ ./install.sh
```
If get wrong change version to 2.7.2

**Comment by BrentonEarl** [comment]
The package built just fine.  Slpkg supplied the slackarm repo as the default slack repository.  "slpkg -c slack --upgrade" ran without errors and I was able to update to the latest change log.

Thank you.
