### ISSUE TITLE
Slackware ARM:  Mirrors that do not support ARM should not be available

### ISSUE THREAD

**Issue by BrentonEarl** [dslackw/slpkg#37]
### Problem

slpkg provides mirrors that do not support the ARM architecture.  Mirrors like 'alien' are built with i486 and x86_64 in mind.  __I tested this only against the 'alien' repository.__

An unsuspecting user may enable one a repository that does not support ARM and could potentially install packages these packages.

### Expected Result
slpkg should only allow users to select mirrors that are available for the current system architecture.  This will prevent ARM systems from installing x86/x86_64 packages.

##### Example Output
```bash
root@raspi:/etc/slpkg# slpkg -v
Version : 2.7.2
Licence : GNU General Public License v3 (GPLv3)
Email   : d.zlatanidis@gmail.com
root@raspi:/etc/slpkg# slpkg -s alien chromium
Reading package lists... Done
Resolving dependencies... Done

The following packages will be automatically installed or upgraded 
with new version:

+==============================================================================
| Package                 New Version        Arch    Build  Repos          Size
+==============================================================================
Installing:
  chromium                44.0.2403.107      i486    1      alien       54336 K

Installing summary
===============================================================================
Total 1 package.
1 package will be installed, 0 will be upgraded and 0 will be reinstalled.
Need to get 53.06 Mb of archives.
After this process, 191.8 Mb of additional disk space will be used.

Would you like to continue [y/N]? 
```
```bash
root@raspi:/etc/slpkg# slpkg -l alien | grep chromium
chromium-44.0.2403.107-i486-1alien.txz
chromium-pepperflash-plugin-18.0.0.233-i386-1alien.txz
chromium-widevine-plugin-44.0.2403.107-i386-1alien.txz
```

**Comment by dslackw** [comment]
I think the field Arch is enough to understand if packages match in your system. I will make a reference to the file /etc/slpkg/slpkg.conf and REPOSITORIES for ARM users.

**Comment by dslackw** [comment]
There repository that are supported on ARM architecture except the slackbuilds.org?

**Comment by BrentonEarl** [comment]
As far as I know, the only supported repositories for ARM are slack and sbo.

**Comment by dslackw** [comment]
Yeah right and I the same.

**Comment by dslackw** [comment]
These changes will be enough to understand.

**Comment by BrentonEarl** [comment]
Yes I agree.
