### ISSUE TITLE
slpkg  Slackware 14.0  -- no "Pasture" directory on any mirrors

### ISSUE THREAD

**Issue by rwwendel** [dslackw/slpkg#39]
slpkg is looking for a couple of flies in "Pasture"    It seems that Slackware 14.0 is about the only
version that does not have a "Pasture" directory in it's tree.   Slpkg update  does not work/complete because it is looking for missing directories and files.
Thanks

**Comment by dslackw** [comment]
Thank you very much I will find as soon as a solution.

**Comment by dslackw** [comment]
Fixed on develop branch.
Thanks again.
