### ISSUE TITLE
issue on reversed version of packages source code.

### ISSUE THREAD

**Issue by metemaddar** [dslackw/slpkg#41]
I tried to install iojs which was 3.1.0 last night.
Today the reversed version (2.5) went on SBo. I updated slpkg and retried to install iojs again; But slpkg used the previous cached slackbuild and source with version of 3.1.

I think it doesn't redownload again if the cached source is newer version.

**Comment by metemaddar** [comment]
Excuse me. I don't know the problem exactly. I'm trying to find out.

**Comment by dslackw** [comment]
One example would help

**Comment by metemaddar** [comment]
1- iojs 3.1.0 was on slackbuilds.
2- I installed it using slpkg
3- updated slpkg; iojs 2.5 went on slackbuilds
4- I tried to install iojs again. slpkg showed iojs 2.5
5- slpkg downloaded iojs 2.5 but was working on iojs 3.1 (extracting iojs-3.1)
6- I removed all the iojs* from /tmp/slpkg/build/
7- slpkg started to build iojs 2.5 this time.
8- at last it got error:
    tar: /tmp/slpkg/build/iojs/iojs-v3.1.0.tar.xz: Cannot open: No such file or directory) error
    tar: Error is not recoverable: exiting now

**Comment by dslackw** [comment]
After run:
```
# slpkg -s sbo iojs
```
[build and install](http://postimg.org/image/urb4widt7/) normal for me with my Slackware 14.1 x86_64 stable and slpkg 2.7.6

**Comment by metemaddar** [comment]
Maybe it's a rare exception on my environment (maybe for cached files). Thanks. I'm trying to install other versions than SBo by hand.

**Comment by dslackw** [comment]
Believer to avoid similar incidents after this patch.
Thank you for your report.
