### ISSUE TITLE
"nvidia-kernel" Fails to install

### ISSUE THREAD

**Issue by Xylemon** [dslackw/slpkg#46]
It seems that slpkg fails to install "nvidia-kernel" from SBo. The following happens:

Slackware package /tmp/nvidia-kernel-352.41_4.1.6-x86_64-1_SBo.tgz created.

Total build time for package nvidia-kernel : 40.61 Sec

+==============================================================================
| Build package nvidia-kernel-352.41 [ FAILED ]
+==============================================================================
| See log file in '/var/log/slpkg/sbo/build_logs' directory or read README
+==============================================================================

It builds fine and creates a package, what gives?

**Comment by websafe** [comment]
@Xylemon what's in the build log?are you able to install the built package with `installpkg`?

**Comment by dslackw** [comment]
There is version difference. In the info file 352.41 with created package 352.41_4.1.6

**Comment by dslackw** [comment]
It is not slkg problem. I will fix the script that will report to admins.

**Comment by dslackw** [comment]
But i will try to found solution via slpkg.

**Comment by Xylemon** [comment]
@websafe Yeah, I was able to.

@dslackw Ah that makes sense, thanks for looking into it.

**Comment by dslackw** [comment]
Fixed in develop branch. Thank you very much @Xylemon

**Comment by Xylemon** [comment]
Glad to hear that, thanks.

**Comment by dslackw** [comment]
@Xylemon check it with version 2.9.6. Thanks

**Comment by Xylemon** [comment]
Built fine and installed no problem. Thanks!

**Comment by Xylemon** [comment]
I actually found a bug related to this commit. Let's say I have an older build of nvidia-kernel from 3.18.11 in the tmp folder, slpkg will actually install the older version rather than the new one. Should add a check so it only installs the latest package.

**Comment by dslackw** [comment]
Thank you, fixed in develop branch as usual.

**Comment by Xylemon** [comment]
Thanks!
