### ISSUE TITLE
slack upgrade dialog shows packages i've not installed

### ISSUE THREAD

**Issue by mtz** [dslackw/slpkg#47]
hi,

i have set up RELEASE=stable in slpkg.conf. 
but if i execute "slpkg -c slack --upgrade" i'll see lot of packages to upgrade what i have not installed.

can u explain?

regards
mtz

**Comment by dslackw** [comment]
Try to change variable ONLY_INSTALLED=on

**Comment by mtz** [comment]
i remember that i've turned on in past. but perhaps an new config file has overwrite my settings. 
now is fine. thanks for quick reply.
