### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by babam86** [dslackw/slpkg#51]
1. Add ability to download packages and dependencies without install (Download Only).

2. I have installed a package manually and could not work because of missing dependencies, what slpkg able to solve that problem.

Thanks.

**Comment by dslackw** [comment]
Ηι @babam86,
Your first request is processed and at work how can be fulfilled.
In the second request to become a little more detailed?

**Comment by babam86** [comment]
For example, I have installed manually File-Roller 'installpkg file-roller-3.16.4-i686-txz' and then File-Roller could not work because of missing dependencies. What slpkg can install the necessary dependencies in this case.

Thanks.

**Comment by dslackw** [comment]
Slpkg takes dependencies from the current repository may not add dependencies if they are not mentioned in the package.

**Comment by dslackw** [comment]
slpkg v3.0.1
They added two options with which you can first download the packages without making install and secondly to redirect the list to be downloaded.

Example:
```
slpkg -s sbo Flask --download-only --directory-prefix=/path/to/dir

```

**Comment by babam86** [comment]
Thank you so much.

2015-11-17 5.50 GMT+08.00, Dimitris Zlatanidis <notifications@github.com>:
