### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by babam86** [dslackw/slpkg#54]
1. Add an option 'd' (Download-Only) when giving the question 'Would you like to continue [y/N/d]?'

2. What are the advantages when using 'slpkg -i <packages>' rather than 'installpkg <packages>', resolving dependencies?

Thanks.

**Comment by dslackw** [comment]
1. This request has completed with option "--download-only". Would prefer the present situation as it is to keep a style throughout the program.

2. No resolving dependencies, it is the same with installpkg command. Read the man page.
