### ISSUE TITLE
MPV: Fails to grab "waf-1.8.12"

### ISSUE THREAD

**Issue by Xylemon** [dslackw/slpkg#56]
The SlackBuild for MPV off SBo requires this file: http://www.freehackers.org/~tnagy/release/waf-1.8.12 however, slpkg always fails to grab it. Any reason why this happens?

**Comment by dslackw** [comment]
Slpkg reads SLACKBUILDS.TXT file and for some reason the waf file does not include it.
Same issue with #50

**Comment by dslackw** [comment]
from SLACKBUILDS.TXT file:
```
SLACKBUILD NAME: mpv
SLACKBUILD LOCATION: ./multimedia/mpv
SLACKBUILD FILES: README doinst.sh mpv.SlackBuild mpv.info slack-desc
SLACKBUILD VERSION: 0.10.0
SLACKBUILD DOWNLOAD: https://github.com/mpv-player/mpv/archive/v0.10.0.tar.gz
SLACKBUILD DOWNLOAD_x86_64:
SLACKBUILD MD5SUM: e81a975e4fa17f500dc2e7ea3d3ecf25
SLACKBUILD MD5SUM_x86_64:
SLACKBUILD REQUIRES: ffmpeg libass docutils
SLACKBUILD SHORT DESCRIPTION:  mpv (a movie player based on MPlayer and mplayer2)
```

**Comment by Xylemon** [comment]
It does seem to be included in the info file though, is there a way for slpkg to possibly grab files from that as well?

**Comment by willysr** [comment]
Fixed on this commit: http://slackbuilds.org/cgit/slackbuilds/commit/?h=willysr&id=af375ab91b614fc6a8c654bd44eb007240f8c870

**Comment by dslackw** [comment]
This issue has been fixed. Thanks Willy !

**Comment by Xylemon** [comment]
Thanks!
