### ISSUE TITLE
Request: Ability to show only package name in list

### ISSUE THREAD

**Issue by Xylemon** [dslackw/slpkg#57]
I would love the ability to see only the package name when I do a listing with slpkg. For instance, if I do "slpkg -l slack --installed", I see:

```
ConsoleKit2-1.0.0-x86_64-3.txz
GConf-3.2.6-x86_64-2.txz
LibRaw-0.17.0-x86_64-1.txz
PyQt-4.11.4-x86_64-1.txz
QScintilla-2.9-x86_64-1.txz
a2ps-4.14-x86_64-5.txz
aaa_terminfo-5.9-x86_64-1.txz
aalib-1.4rc5-x86_64-5.txz
```

I would desire to see a listing like this:

```
ConsoleKit2
GConf
LibRaw
PyQt
QScintilla
a2ps
aaa_terminfo
aalib
```

Could such a variable be added?

**Comment by dslackw** [comment]
Added in develop branch with extra option "--name".

**Comment by dslackw** [comment]
slpkg v3.0.8 released and added this request.

**Comment by Xylemon** [comment]
Thank you! This is extremely helpful for a script I was writing!

**Comment by dslackw** [comment]
Glad to help!
