### ISSUE TITLE
List only shows updated applications?

### ISSUE THREAD

**Issue by Xylemon** [dslackw/slpkg#58]
I've noticed that when listing installed applications, at least with the slack repo, it seems to only list applications that are fully update to date, and un-updated applications are not listed. Surely this is a bug right?

Tested under slpkg 3.0.8

**Comment by dslackw** [comment]
A simple example will help

**Comment by Xylemon** [comment]
Sure:

```
slpkg -l slack --installed       

ConsoleKit2-1.0.0-x86_64-3.txz
GConf-3.2.6-x86_64-2.txz
LibRaw-0.17.0-x86_64-1.txz
PyQt-4.11.4-x86_64-1.txz
QScintilla-2.9-x86_64-1.txz
a2ps-4.14-x86_64-5.txz
aaa_terminfo-5.9-x86_64-1.txz
aalib-1.4rc5-x86_64-5.txz
acct-6.5.4-x86_64-2.txz
```

Some packages above are missing, and they just happen to be un-updated applications:

```
slpkg -c slack --upgrade
Checking... Done
Reading package lists... Done
Resolving dependencies... Done

The following packages will be automatically installed or upgraded 
with new version:

+==============================================================================
| Package                 New Version        Arch    Build  Repos          Size
+==============================================================================
Upgrading:
  xorg-cf-files-1.0.5     1.0.6              x86_64  2      slack         184 K
  vbetool-1.1             1.2.2              x86_64  1      slack          16 K
  sharutils-4.15          4.15.2             x86_64  1      slack         260 K
  rsync-3.1.1             3.1.2              x86_64  1      slack         304 K
  quota-3.17              4.03               x86_64  1      slack         220 K
  pycurl-7.19.0           7.19.5.3           x86_64  2      slack          64 K
  pycups-1.9.70           1.9.73             x86_64  1      slack          68 K
  poppler-0.38.0          0.40.0             x86_64  1      slack        1340 K
  pixman-0.33.4           0.33.6             x86_64  1      slack         236 K
  partitionmanager-1.0.3_20130328svn 1.1.1              x86_64  2      slack        2060 K
  openvpn-2.3.6           2.3.9              x86_64  1      slack         348 K
  openobex-1.5            1.7.1              x86_64  1      slack         144 K
  nfs-utils-1.3.1         1.3.3              x86_64  1      slack         220 K
  network-manager-applet-1.0.8 1.0.10             x86_64  1      slack        1036 K
  mesa-11.0.7             11.1.1             x86_64  1      slack        8288 K
  mcabber-0.10.2          1.0.0              x86_64  1      slack         232 K
  lvm2-2.02.137           2.02.138           x86_64  1      slack        1176 K
  lsof-4.83               4.89               x86_64  1      slack         288 K
  libssh-0.6.4            0.7.2              x86_64  1      slack         192 K
  libdrm-2.4.65           2.4.66             x86_64  1      slack         196 K
  libcroco-0.6.10         0.6.11             x86_64  1      slack         212 K
  libXi-1.7.5             1.7.6              x86_64  1      slack         184 K
  kernel-source-4.1.15    4.4                noarch  1      slack       88800 K
  kernel-modules-4.1.15   4.4                x86_64  1      slack       28232 K
  kernel-huge-4.1.15      4.4                x86_64  1      slack        7716 K
  kernel-headers-4.1.15   4.4                x86     1      slack         732 K
  kernel-generic-4.1.15   4.4                x86_64  1      slack        4500 K
  ghostscript-9.16        9.18               x86_64  2      slack       14684 K
  fuse-2.9.3              2.9.4              x86_64  1      slack         144 K
  curl-7.45.0             7.46.0             x86_64  1      slack        1060 K
  cups-filters-1.4.0      1.6.0              x86_64  1      slack         676 K
  aaa_base-14.1           14.2               x86_64  1      slack          12 K
  NetworkManager-1.0.8    1.0.10             x86_64  3      slack        2880 K
  M2Crypto-0.22.3         0.22.5             x86_64  1      slack         188 K
```

**Comment by dslackw** [comment]
Command:
``slpkg -l slack --installed``
show only installed packages from slack repository

Command:
``slpkg -c slack --upgrade``
show all packages needed for install or upgrade

**Comment by Xylemon** [comment]
But why is "slpkg -l slack --installed" not listing the packages I haven't updated? They're installed on my system, shouldn't they show up in the list?

**Comment by dslackw** [comment]
Please tell me what you version Slackware use -current or -stable?

**Comment by Xylemon** [comment]
It's an install of Stable that I basically updated to Current, since I've updated every package on the system. The slpkg.conf is also set to "current"

**Comment by dslackw** [comment]
Try to upgrade package list:
``slpkg upgrade --only=slack``

**Comment by Xylemon** [comment]
Same result, how does slpkg detect what you have installed from a repo?

**Comment by dslackw** [comment]
Please check if there is a difference between the two commands:
``slpkg -l slack --installed`` 
and
``slpkg -l slack --installed --name``

**Comment by dslackw** [comment]
"Same result, how does slpkg detect what you have installed from a repo?"

slpkg read PACKAGES.TXT file and check if package exist in /var/log/packages directory.

**Comment by Xylemon** [comment]
Both  "slpkg -l slack --installed | wc -l" and "slpkg -l slack --installed --name | wc -l" report out "894".

**Comment by Xylemon** [comment]
If I had to guess what's going on, it would be that when slpkg reads from PACKAGES.TXT and compares the packages from /var/log/packages, it's check the full package file name instead of just the name of the package.

So slpkg sees "PACKAGE NAME:  aaa_base-14.2-x86_64-1.txz" in PACKAGES.txt but instead finds "aaa_base-14.1-x86_64-1" in "/var/log/packages", at least that's I think is going on here.

**Comment by dslackw** [comment]
No, it is ok.
slpkg compare package without suffix.

But i still confused with this issue, I think slpkg work correctly.

If your package from slack repo is installed then printed?

**Comment by Xylemon** [comment]
Yes, the packages not showing up in the list of installed packages. The only reason why I can see they're not showing up is because they're not updated. If I update an application, it then shows up when I do "slpkg -l slack --installed", but un-updated applications still do not show up. I do not thin slpkg is functioning correctly unless the intention for listing packages from a repo was to show only updated packages.

**Comment by dslackw** [comment]
Yes, if package version is different.

**Comment by Xylemon** [comment]
So I guess what I'm asking is, can slpkg have an option to show all installed packages regardless of package version?

**Comment by dslackw** [comment]
```
slpkg -f <package_name>
```

**Comment by dslackw** [comment]
```
slpkg -l <repository> --installed
```
not matching packages but compare package equal package

**Comment by Xylemon** [comment]
So there is just no way to display all packages installed from a repo regardless of package version?

**Comment by dslackw** [comment]
Fixed in develop branch.
If use option "--name" then check packages with the name.

**Comment by Xylemon** [comment]
Thank you, just tried it and it lists all the installed packages properly.
