### ISSUE TITLE
slpkg, Salix OS and 14.1 multilib system.

### ISSUE THREAD

**Issue by globetrotterdk** [dslackw/slpkg#60]
I have been unable to find any documentation as to how to use slpkg to upgrade to a multilib system. I am using slpkg on a Salix64 14.1 Mate system. Ineed to enable Alien's multilib repository and then?

**Comment by dslackw** [comment]
```
slpkg -c alien --upgrade
```

**Comment by globetrotterdk** [comment]
Thanks :-)
