### ISSUE TITLE
Repo Support: Ponce's SBo Fork

### ISSUE THREAD

**Issue by Xylemon** [dslackw/slpkg#61]
Could there be support for Ponce's SBo Fork: https://github.com/Ponce/slackbuilds ? It's a great repo for current users as his repo fixes SlackBuilds that break. I'm not quite sure how slpkg could support it because there isn't a PACKAGES.TXT but if it's any consolation, sbopkg supports it.

**Comment by dslackw** [comment]
Not for SBo but binary repository. You can use it with:
```
slpkg repo-add ponce http://ponce.cc/slackware/slackware64-14.1/packages/

```
for Slackware64

or http://ponce.cc/slackers/repository/ for current
or whatever mirror you want.

**Comment by Xylemon** [comment]
Yes, but I was asking in particular if that repo could be added, I am aware of his package based repo.

**Comment by dslackw** [comment]
Unfortunately at this point slpkg has designed to work with only SBo (slackbuilds.org) repository. Ponce repository looks like is a git repository and work very different with sbopkg tool.
Maybe in future i will try to added this request.

**Comment by Xylemon** [comment]
I would greatly appreciate it. Also, to avoid any confusion, I wouldn't want this repo to be a part of the existing SBo repo, I would want it to be a third party repo the user could enable.

**Comment by keeely** [comment]
The need for this increases with every month passing without 15.0 release :-(.
