### ISSUE TITLE
Old (v3.0.5) on slackbuilds.org

### ISSUE THREAD

**Issue by websafe** [dslackw/slpkg#62]
Hello @dslackw, 

nothing critical, but there's **v3.0.5** on SlackBuilds.org https://slackbuilds.org/repository/14.1/system/slpkg/?search=slpkg and AFAIR v3.0.5 has some problems. Maybe it's a good idea to submit an update?

:-)

**Comment by dslackw** [comment]
As has been mentioned to me by @willysr repository 14.1 has been closed for updates.

**Comment by websafe** [comment]
OK, so we probably can expect 14.2 coming soon :-)
