### ISSUE TITLE
Applying patch to slackbuild script while installing with slpkg.

### ISSUE THREAD

**Issue by globetrotterdk** [dslackw/slpkg#63]
Is it possible to apply a patch to a slackbuild script while installing with slpkg? I would like to install Musescore 2 as described here [http://www.linuxquestions.org/questions/slackware-14/how-to-build-musescore-2-0-1-a-4175547799/](url) but I am new to Slackware and have never tried to do this. I was hoping that this could be done with slpkg.

**Comment by dslackw** [comment]
What exactly do you mean? and link is dead.

**Comment by globetrotterdk** [comment]
The Slackbuild version of Musescore (mscore) is 1.3. However, there is a Slackbuild script patch that is available to instead build the 2.0.1 version of mscore. Is it possible to apply a patch when running the command # slpkg -s sbo mscore ?

The link is OK, but GitHub reports it as dead for some reason.

**Comment by dslackw** [comment]
No, unfortunately, this is probably a work of mscore maintainer.

**Comment by websafe** [comment]
@dslackw  the link should be http://www.linuxquestions.org/questions/slackware-14/how-to-build-musescore-2-0-1-a-4175547799/ @globetrotterdk's link is somehow pointing to https://github.com/dslackw/slpkg/issues/url :-)

**Comment by globetrotterdk** [comment]
I received the following reply from SourceForge:

> We somewhat recently switched from HTTP to HTTPS which is creating issues for some users when trying to redirect to the HTTPS version.
Try using HTTPS in your calls instead of HTTP.

Should this be reflected in the slpkg setup?

**Comment by dslackw** [comment]
I do not think there is a problem.
