### ISSUE TITLE
Working with custom local repositories

### ISSUE THREAD

**Issue by denydias** [dslackw/slpkg#65]
Hi there,

I'm looking to streamline my package/slackbuilds management. slpkg seems to fit my needs.

For years now I have my own local repository mirrors. This has proved to speed up things a lot when dealing with system upgrades. So I really wish to keep it as it is today. This structure is like:

* **Local repositories:**

  * slack mirror: file:///mnt/slackware64-current/
  * multilib mirror: file:///mnt/alienbob/multilib/
  * sbo-git mirror: file:///var/lib/sbopkg/SBo-git/
  * my packages: file:///mnt/slackbuilds/pkg64/

* **Custom Remote repositories:**

  * acur64: http://bear.alienbase.nl/mirrors/people/alien/sbrepos/current/x86_64/
  * rest64: http://bear.alienbase.nl/mirrors/people/alien/restricted_sbrepos/current/x86_64/
  * slckyc: http://repository.slacky.eu/slackware64-14.1/
  * slpkg+: http://slakfinder.org/slackpkg+/

I have set this under slpkg configuration files. The local repositories paths points to the same URI above, as I've seen that slpkg [is supposed to work with file:// scheme](http://www.linuxquestions.org/questions/slackware-14/slpkg-new-slackware-packaging-tool-4175516588/page7.html#post5381299) for local repositories.

So I can use the `file://` schema, which is [not supported by wget](https://daniel.haxx.se/docs/curl-vs-wget.html), I have changed `slpkg.conf` to read:

```
DOWNDER=curl
DOWNDER_OPTIONS=-L -o
```

With everything set, I run `slpkg update` and get this output (successful stuff is suppressed):

```
# slpkg update

Check and update repositories:

Check repository [slack] ... Done
Check repository [denydl] ... Done
Check repository [multil] ... 
[1/1][ Download ] --> ChangeLog.txt

curl: (37) Couldn't open file /mnt/alienbob/multilib/ChangeLog.txt

+==============================================================================
| Download 'ChangeLog.txt' file [ FAILED ]
+==============================================================================


[1/1][ Download ] --> PACKAGES.TXT

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  123k  100  123k    0     0   328M      0 --:--:-- --:--:-- --:--:--  328M

[1/1][ Download ] --> CHECKSUMS.md5

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  110k  100  110k    0     0   294M      0 --:--:-- --:--:-- --:--:--  294M

[1/1][ Download ] --> ChangeLog.txt

curl: (37) Couldn't open file /mnt/alienbob/multilib/ChangeLog.txt

+==============================================================================
| Download 'ChangeLog.txt' file [ FAILED ]
+==============================================================================

Done
Check repository [sbogit] ... 
[1/1][ Download ] --> PACKAGES.TXT

curl: (37) Couldn't open file /var/lib/sbopkg/SBo-git/PACKAGES.TXT

+==============================================================================
| Download 'PACKAGES.TXT' file [ FAILED ]
+==============================================================================


[1/1][ Download ] --> CHECKSUMS.md5

curl: (37) Couldn't open file /var/lib/sbopkg/SBo-git/CHECKSUMS.md5

+==============================================================================
| Download 'CHECKSUMS.md5' file [ FAILED ]
+==============================================================================

Done
Check repository [acur64] ... 
[1/1][ Download ] --> PACKAGES.TXT

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  203k  100  203k    0     0   175k      0  0:00:01  0:00:01 --:--:--  176k

[1/1][ Download ] --> CHECKSUMS.md5

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  165k  100  165k    0     0   140k      0  0:00:01  0:00:01 --:--:--  140k

[1/1][ Download ] --> ChangeLog.txt

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   255  100   255    0     0    561      0 --:--:-- --:--:-- --:--:--   573
Done
Check repository [rest64] ...
[1/1][ Download ] --> PACKAGES.TXT

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2383  100  2383    0     0   5309      0 --:--:-- --:--:-- --:--:--  5403

[1/1][ Download ] --> CHECKSUMS.md5

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2593  100  2593    0     0   5855      0 --:--:-- --:--:-- --:--:--  5947

[1/1][ Download ] --> ChangeLog.txt

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   266  100   266    0     0    596      0 --:--:-- --:--:-- --:--:--   603
Done
Check repository [slckyc] ... Done
Check repository [slpkg+] ... Done
```

The files that were not found aren't part of the source repositories.

Now, I run:

```
# slpkg -c ALL

  Please update packages lists. Run 'slpkg update'.
  This command should be used to synchronize packages
  lists from the repositories are enabled.

# slpkg -c slack

  Please update packages lists. Run 'slpkg update'.
  This command should be used to synchronize packages
  lists from the repositories are enabled.
```

Why is that? Are those missing files required for slpkg operation? If so, how one can work with local or remote repositories that lacks those optional repositories metadata files?

Or maybe I'm just plain wrong in my assumptions for a slpkg workflow. =P

For the record:

```
# slpkg -v
Version   : 3.1.2
Licence   : GNU General Public License v3 (GPLv3)
Email     : d.zlatanidis@gmail.com
Maintainer: Dimitris Zlatanidis (dslackw)
```

**Comment by dslackw** [comment]
Sorry for the delay, I think I'm close to a solution and soon will I have a solution for this issue.

**Comment by denydias** [comment]
Nice, @dslackw! If I can be of any help, please let me know.

**Comment by denydias** [comment]
Oh! One question: so I can properly manage a system with slpkg, do I need to use it from start? Can slpkg 'snapshot' the installed packages and take control from there?

**Comment by dslackw** [comment]
Yes you can.

**Comment by denydias** [comment]
Great! Better than Obama did! :stuck_out_tongue_closed_eyes:

**Comment by qyur** [comment]
Am I understanding correctly that to use slpkg with local repository of sbo-git one just have to generate the PACKAGES, CHECKSUMS.md5 and Changelog locally?  The Changelog seems the most difficult part.

**Comment by denydias** [comment]
@qyur, I'm not using slpkg yet because it can't handle my setup atm.

SBo-git is just one of the repositories I mirror locally. Besides it, I also have these local mirror repos:

- `file://mnt/mirrors/slackware64-current/`: Slackware64-current.
- `file://mnt/mirrors/alienbob/multilib/`: AlienBob's multilib.
- `file://mnt/mirrors/pkg64/`: my own packages.

All the above are standard repositories sporting the expected metadata files (CHECKSUMS.md5.gz, ChangeLog.txt.gz, MANIFEST.bz2, PACKAGES.TXT.gz and such). SBo-git is the only one to have just Changelog.txt and no other control file.

**Comment by dslackw** [comment]
Hi again, sorry for delay.
slpkg v3.1.3 is ready to relase and support local sbo repository but to work correctly must replace SLACKBUILDS.TXT file in directory "/var/lib/slpkg/sbo_repo/".

**Comment by denydias** [comment]
No problem. I'm out of office for the moment. Get back to you next week.

Tks.
