### ISSUE TITLE
Unable to run "slpkg update" on Current (SlackBuilds)

### ISSUE THREAD

**Issue by mtslzr** [dslackw/slpkg#66]
Sorry for double-dipping with #64, but similar problem here. Running a fresh Slackware -current install, and no matter what I do (currently have "current" set in slpkg.conf and haven't touched repos), it fails with a 404 on SlackBuilds.org. Largely because it's trying to grab a sub-folder of 14.2 (like above) and failing.

I noticed the README mentioned setting a VERSION variable, but I've put that in /etc/slpkg/slpkg.conf and passed it on the same line as "slpkg update" and neither makes a difference. Is there something dumb I'm missing for running this with current?

**Comment by dslackw** [comment]
This will have to wait until Slackware 14.2 is released temporarily or change the version in the file "/etc/slackware-version" in 14.1

**Comment by mtslzr** [comment]
Gotcha; was thinking it was probably just an in-between-versions issue. Oh well, thank you!
