### ISSUE TITLE
Downloading sbo SLACKBUILDS.TXT fails

### ISSUE THREAD

**Issue by heydojo** [dslackw/slpkg#67]
Please see the the linked image for the output of the console when I run slpkg update for the first time:
https://drive.google.com/open?id=0B45Yi_r5mamwNUxCVFZSaklPYW8
Basically, I think that at some point sbo have started using https?
wget requires the --no-check-certificate switch in order to download without the cert installed.

Is it possible to make the --no-check-certificate switch the default for sbo?
Is there a way around this by adding a switch to slpkg update?
Thanks.

**Comment by dslackw** [comment]
Try to add wget flag "--no-check-certificate" in slpkg.conf file, like:
```
# Downloader [OPTION]. Pass downloader options, for curl use "-L -o" as
# using to download in specific directory and support any redirects
# such as from sourceforge repository. No extra option need for aria2c
# by default to work. Http recommended "-d -c -o" options by default.
# Default for wget is "-c -N".
DOWNDER_OPTIONS=-c -N --no-check-certificate
```

**Comment by heydojo** [comment]
That worked a treat. Thanks!
