### ISSUE TITLE
Update only one repository and check and upgrade packages from it

### ISSUE THREAD

**Issue by qyur** [dslackw/slpkg#69]
If I only want to update the available packages from one repository, it seems that I should issue the command:
```
# slpkg update --only=sbo                                                           

Check and update repositories:

Check repository [sbo] ... Done
```

it seems to run fine.
But when I try to possibly upgrade all packages installed from that repository, slpkg demands that I update lists of packages from ALL repositories, or am I wrong?

```
# slpkg -c sbo --upgrade                                                            

  Please update packages lists. Run 'slpkg update'.
  This command should be used to synchronize packages
  lists from the repositories are enabled.


```

**Comment by dslackw** [comment]
It works well to me. It seems that another repository has not updated.

**Comment by qyur** [comment]
Hi Dimitris,

I'll try to make myself clearer in order to ask if the `slpkg` behavior is desirable as it is or not.

My case:  I'm using slpkg with 'stable' and have a few repositories active, including `slackr`.
I want to check if I can upgrade packages from sbo only, so I issue a `slpkg update` command.

When `slpkg` tries to update `slackr` it fails:
```
Check repository [slackr] ... 
[1/1][ Download ] --> PACKAGES.TXT

--2016-07-11 10:39:50--  http://slack.conraid.net/repository/PACKAGES.TXT
A resolver slack.conraid.net (slack.conraid.net)...87.98.219.121
A conectar slack.conraid.net (slack.conraid.net)|87.98.219.121|:80... conectado.
Pedido HTTP enviado, a aguardar resposta...404 Not Found
2016-07-11 10:39:50 ERRO 404: Not Found.


+==============================================================================
| Download 'PACKAGES.TXT' file [ FAILED ]
+==============================================================================

Would you like to continue [y/N]? 
```

So, as I only intended to use `sbo` I tried  to only update `sbo` with 
```
# slpkg update --only=sbo                                                           

Check and update repositories:

Check repository [sbo] ... Done
```

Ok, I thought now I can check if `sbo` has updated versions of packages I have installed.  But when I run:
```
# slpkg -c sbo

  Please update packages lists. Run 'slpkg update'.
  This command should be used to synchronize packages
  lists from the repositories are enabled.
```
`slpkg` doesn't allow me to do that, instead it imposes that every repository is updated even though one repository can be down at the moment.

I think that it'd be desirable that `slpkg` could update just a repository and enable a user to check updated packages in that repository only.

Thank you for this very nice tool!

**Comment by dslackw** [comment]
Activated repositories will be created primarily.
Disable the repositories that are not working.

**Comment by dslackw** [comment]
Fixed in develop branch and merged in next version.
Thank you.
