### ISSUE TITLE
Command "slpkg -F" maybe not always working properly

### ISSUE THREAD

**Issue by Sybelius** [dslackw/slpkg#70]
I am writing to inform about a small problem using "slpkg", or is me doing mistake and I don't realize or it is inattentive some times. I mean: more than a time using the function
# slpkg -F package-name I don't get the wanted one and... going to visit a repository (SlackBuilds.org, for instance) I see the package there.
Installed on Slackware 14.2 KDE 64 Bit (huge kernel) and updated to the last available version (v3.1.7).
Repositories activated:
- Alien
- SBo
- Slack
Best Regards

**Comment by dslackw** [comment]
Have you tried the command:
```
slpkg -n <package>
```
This command working only for SBo repository.
You can try the extra option "--case-ins"

**Comment by Sybelius** [comment]
Thank you! - I take note of that command.
