### ISSUE TITLE
Package versions differ - error to build

### ISSUE THREAD

**Issue by lpvm** [dslackw/slpkg#72]
Hi,

This is happening to **youtube-dl**, but has happened before to other packages, although in time, after a few days, things went fine.  It seems some dis-synchronization.
Please check this:

When 
```
# slpkg -s sbo youtube-dl
Installing:
  youtube-dl              2016.09.08         x86_64         SBo
```

I say yes and then:

```
 MD5SUM check for 2016.09.08.tar.gz [ PASSED ]
+==============================================================================

tar: /tmp/slpkg/build/youtube-dl/youtube-dl-2016.09.24.tar.gz: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
tar: /tmp/slpkg/build/youtube-dl/2016.09.24.tar.gz: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
```

So, it downloads the file from the 8th of September, but would like to have the newer file from the 24th of September.  The latter file is, in fact, the one available in Slackbuilds.org at the moment.

Can you please check this out and tell of a fix to this?
Thanks for all the hard work!

**Comment by dslackw** [comment]
You tried to upgrade packages lists before;
```
slpkg update
```

**Comment by lpvm** [comment]
You're right!
I'll add `slpkg update` to run in cron every night, not to have to wait for it to finish.
Thank you.
