### ISSUE TITLE
develop branch problem - Error: Repository name 'studio' is not default name.

### ISSUE THREAD

**Issue by websafe** [dslackw/slpkg#74]
Trying to check changes solving #73  with develop branch, but:

~~~~
# slpkg update   

slpkg: Error: Repository name 'studio' is not default name.
              Please check file: /etc/slpkg/default-repositories
~~~~

I had to comment out `studio` in `/etc/slpkg/default-repositories` to get it working.

**Comment by dslackw** [comment]
I have removed studio repository. Please see changes in /etc/slpkg path.

**Comment by websafe** [comment]
OK
