### ISSUE TITLE
Machine readable deps list

### ISSUE THREAD

**Issue by websafe** [dslackw/slpkg#76]
Hello @dslackw 

would it be possible in the future to enhance `--check-deps`
with a more "machine-readable" output  to be used in an
automated build environment we're discussing here:  

 + https://lists.slackbuilds.org/pipermail/slackbuilds-users/2016-November/017419.html
 + https://lists.slackbuilds.org/pipermail/slackbuilds-users/2016-November/017446.html

I'm not sure about the expected format, I'm just announcing this to make you aware
of the ongoing discussion :-)

**Comment by dslackw** [comment]
Thank you Thomas,
I am waiting to report me the output format and I see if it possible for slpkg.
