### ISSUE TITLE
exit codes - another scenario of #73

### ISSUE THREAD

**Issue by websafe** [dslackw/slpkg#79]
Hello @dslackw,

another scenario related to #73 

This code will return `OK` instead of the expected `ERROR`:

~~~~
if echo "Y" | slpkg -s sbo libcacard; then echo "OK"; else echo "ERROR"; fi
~~~~

This should build `libcacard` which requires `pcsc-lite` as a dependency.
`pcsc-lite` requires a special group (`pcscd`) and user (`pcscd`).

So building `pcscd` without creating this group and user will FAIL,
but `slpkg` will continue and build `libcacard`.

~~~~
+==============================================================================
| MD5SUM check for pcsc-lite-1.8.14.tar.bz2 [ PASSED ]
+==============================================================================

  You must have a "pcscd" group to run this script.
    # groupadd -g 257 pcscd
Total build time for package pcsc-lite : 0.1 Sec

+==============================================================================
| Build package pcsc-lite-1.8.14 [ FAILED ]
+==============================================================================
| See log file in '/var/log/slpkg/sbo/build_logs' directory or read README
+==============================================================================


[1/1][ Download ] --> libcacard.tar.gz
~~~~
...
~~~~
Package libcacard-2.5.2-x86_64-1_SBo.tgz installed.


Completed!

+==============================================================================
| Total 1 package installed and 0 package upgraded
+==============================================================================
| Package libcacard-2.5.2 installed successfully
+==============================================================================

OK
~~~~

Expected behavior: terminate execution with exit code other than 0
right after `pcsc-lite` fails.

Otherwise using `slpkg` in scripts will be complicated and require output parsing.

**Comment by dslackw** [comment]
Hi @websafe,
I have made the change, can you try again?

**Comment by websafe** [comment]
Hi @dslackw, I'm sorry, I'm very busy at the moment at work, I will check this out on thursday or friday, OK?

**Comment by websafe** [comment]
It took me a long time to answer ;-) but I've tested this now and your changes work as expected 👍

**Comment by dslackw** [comment]
Yes Thomas and Thank you again for the confirmation!
