### ISSUE TITLE
I can't install filezilla

### ISSUE THREAD

**Issue by inukaze** [dslackw/slpkg#80]
Hi there again, when i try to install filezilla, the slpkg, just ignore, and finish 

```
#$ slpkg -s sbo filezilla
Reading package lists... Done
Resolving dependencies... Done

The following packages will be automatically installed or upgraded 
with new version:

+==============================================================================
| Package                 New version        Arch    Build  Repos          Size
+==============================================================================
Installing:
  filezilla               3.24.0             x86_64         SBo
Installing for dependencies:
  wxGTK3-3.0.2            3.0.2              x86_64         SBo
  libfilezilla            0.9.0              x86_64         SBo

Installing summary
===============================================================================
Total 3 packages.
2 packages will be installed, 1 already installed and 0 package
will be upgraded.

Would you like to continue [y/N]?
```

No let me press "y" or "N" on the keyboard for answer, just finish the process. but i dont know why, how i force "y" in the answer ???

**Comment by dslackw** [comment]
This is not happening to me. Can you upgrade package lists?
```
slpkg upgrade --only=sbo
```
and then try again to install filezilla

**Comment by inukaze** [comment]
Its the same. i notice this just happend with i use "root" user (from CLI)
but if i use my user, with command

`su -c "slpkg -s sbo filezilla" root`

works fine. but i think the idea is works in both case, no?

**Comment by dslackw** [comment]
Please open the configuration file /etc/slpkg/slpkg.conf and check the variable DEFAULT_ANSWER

**Comment by inukaze** [comment]
`su -c "joe /etc/slpkg/slpkg.conf" root`


```
# Define default answer to slpkg questions.
# Choose "y" if you do not want to questions. Default is "n".
DEFAULT_ANSWER=n
```

Ok y switch to "y" , i have a litte suggestions , in the config files not exist a default "passing variables" files a simple files for example for "LibreOffice.pass" and inside put 

```
LOLANGS="ALL"
#LOLANGS="en" # Install English Language
#LOLANGS="es" # Instala el Idioma Español
#LOLANGS="jp"  # 日本語をインストールします。
#LOLANGS="fr"  # Installer la langue française
#LOLANGS="it"   # Installare la lingua italiana
#LOLANGS="pt"  # Instalar o idioma Português
```

For example, or method to pass that variable when the user install LibreOffice from "sbo" for example, because yesterday i have LibreOffice in Spanish (i am from venezuela), and when i upgrade the packages from "sbo" my "LibreOffice" has updated from "5.2" (Spanish) to "5.3" (English) the slpkg never ask if i want a different language or get the language from system.

i install LibreOffice before know the slpkg, directly from SlackBuild site, because of that i specify the language in the old installation.

well i try the change of "DEFAULT_ANSWER=y"
yes now is working :) 

But in that variable, should not be a third option to force "ask" or wait user answer "y" or "n" ???

**Comment by dslackw** [comment]
Thanks for the examples, I will see your suggestions and I modified some configurations.

Please give me an example how maybe works the third option?

**Comment by inukaze** [comment]
Well for force "ask", i try in bash with something like : 

```
DEFAULT_ANSWER=$(awk '/DEFAULT_ANSWER=/{print $NF}' /etc/slpkg/slpkg.conf | sed -n '1 s/^[^=]*= *//p')

if [ "$DEFAULT_ANSWER" = "a" ]; then
while true; do
    read -p "Do you wish to install this program? " yn
    case $yn in
        [Yy]* ) make install; break;;
        [Nn]* ) exit;;
        * ) echo "Please answer yes or no.";;
    esac
done
fi
```

Well is just an example,

**Comment by dslackw** [comment]
I can't understand what you mean. I have two options "y" and "n" in the DEFAULT_ANSWER, if you choose "y" slpkg  skips question if you choose "n" slpkg wait for input. Your suggestion is a third  option "a" like with option "n". It is correct?

**Comment by inukaze** [comment]
Ok if i am using "root" user, and the default answer is "n" , this not wait for user input, assume "n" like answer, and not install package, if is yes then install packages.

but if i run with my normal use : 
`su -c "slpkg -s <repo> <package>" root`

and the default answer is "n" then yes wait for user input, this not happen if i change to root, using : 
`su`

you understand me now ?

**Comment by dslackw** [comment]
Strange, but this is not happening to me.
Work with directly "root" and with "su -c "..." root

[https://postimg.org/image/vlpz6pb2f/](url)

**Comment by inukaze** [comment]
Ok i go switch the default answer to "n" again, yesterday i have a weird issue with the "+" in multimedia keyboard for increase volume . i ever put the command "amixer -q set Master 3%+" to the key "XF86AudioRaiseVolume" 

i dont know this just leave works normally, when i switch to another key, and put again the key "XF86AudioRaiseVolume" start works again - 

Well, with this default answer when i switch to "n" again, works again too :v
