### ISSUE TITLE
OpenGL 32-Bits Libs after upgrade

### ISSUE THREAD

**Issue by inukaze** [dslackw/slpkg#81]
Hi again there. 2 days ago. i update all paquetes from "sbo" repository. using

"slpkg -c sbo --upgrade"

i restarted and all, looks normally, when , in this moment i try to run 

"PlayOnLinux" and show me a "DialogBox Message" "OpenGL32 Libs not found"
i ignore and continue, and close PlayOnLinux.

i open Steam, appear a xterm windows with message : 

```
You are missing the following 32-Bit libraries, and Steam may not run: 
libnvidia-tls.so.304.131
libnvidia-glcore.so.304.131
Press enter to continue:
```

Ok 2 days ago, i had installed  : 
nvidia-legacy304-{driver,kernel} (Version 304.131)

The upgrade install
nvidia-legacy304-{driver,kernel} (Version 304.135)

But something looks miss during the process, making the missing 32-Bits libs for OpenGL.

I'll go to search more information about this error under Slackware64 14.2

**Comment by inukaze** [comment]
Ok readying this "https://www.slackbuilds.org/repository/14.2/system/nvidia-legacy304-driver" 
says

1 ) Backup xorg.conf :  
2 ) execute : nvidia-switch --remove
3 ) remove the files (on my case): 
/usr/lib64/libGL.so.1.2
/usr/lib64/xorg/modules/extensions/{libglx.so libglx.la}

Really the follow file
        /usr/lib64/xorg/modules/extensions/libglx.la
?

i do the follow : 
```
su
rm -rf /usr/lib/libGL.so
rm -rf /usr/lib/libGL.so.304.131
rm -rf /usr/lib64/libGL.so.304.131
rm -rf /usr/lib64/xorg/modules/extensions/libglx.so #This must be a symbolic link to -> libglx.so.304.135
rm -rf /usr/lib64/xorg/modules/extensions/libglx.so-xorg #This must be a "sl" to -> libglx.so.304.135
rm -rf /usr/lib64/xorg/modules/extensions/libglx.so.304.131
cd "/usr/lib64/xorg/modules/extensions"
ln -s "libglx.so.304.135-nvidia" "libglx.so.304.135"
ln -s "libglx.so.304.135" "libglx.so-xorg"
ln -s "libglx.so.304.135" "libglx.so"

[~]#$ cd /usr/lib64
[lib64]#$ ls -la {libGL.so,libGL.so.304.135}
lrwxrwxrwx 1 root root      16 feb 20 23:42 libGL.so -> libGL.so.304.135
-rwxr-xr-x 1 root root 1076560 feb 19 20:53 libGL.so.304.135

[lib]#$ ls -la {libGL.so,libGL.so.304.135}
ls: can not access 'libGL.so.304.135': There is no file or directory
lrwxrwxrwx 1 root root 16 ene 29 00:37 libGL.so -> libGL.so.304.131

```

Ok that is the cause of error with OpenGL32 Lib, the version of 32 Bit, don't exist, the file "libGL.so.304.135" and not is the right symbolic link.

Ok i try using slpkg :  
```
[lib]#$ slpkg -s sbo --rebuild --reinstall nvidia-legacy304-driver

[lib]$ ls -la {libGL.so,libGL.so.304.135}
ls: no se puede acceder a 'libGL.so': No existe el fichero o el directorio
ls: no se puede acceder a 'libGL.so.304.135': No existe el fichero o el directorio
```

Its the same, the package is not using the "OpenGL 32 Bits" libs. well tomorrow when i finish my direct download i try the follow : 

```
init 2
cd /tmp/slpkg/build/_SOURCES
sh NVIDIA-Linux-x86_64-304.135.run

```

**Comment by inukaze** [comment]
Well i have wrote an email for the mantainer of that SlackBuild Package. with the follow content : 

Hi there. i am Slackware64 14.2 user, and i use "slpkg"
Well i Upgrade my system, and the upgrade, update nvidia-legacy304-driver from 304.131 to 135
i put that on the follow url -> https://github.com/dslackw/slpkg/issues/81
Well after i check this :  https://slackbuilds.org/repository/14.2/system/nvidia-legacy304-driver/

i notice, i need make some changes in the Script ( i had COMPAT32 installed ) and i use because i use Steam and PlayOnLinux

i must change the follow manually :

```
# Set 32-bit compatibility flag default
  COMPAT32=${COMPAT32:-no}
```

to 
`  COMPAT32=${COMPAT32:-yes}`

Thinking about it, i had the follow idea to add in the SlackBuild script:

```
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2 -fPIC"
  TARGET="x86_64"
  LIBDIRSUFFIX="64"
# Set 32-bit compatibility flag default
  COMPAT32=${COMPAT32:-no}
```

this should be another if, something like :

```
if [ "$ARCH" = "x86_64" ]; then
	SLKCFLAGS="-O2 -fPIC"
	TARGET="x86_64"
	LIBDIRSUFFIX="64"

# Set 32-bit compatibility flag default
	Link_libGL32=/usr/lib/libGL.so


if [ -L ${Link_libGL32} ] ; then
	if [ -e ${Link_libGL32} ] ; then
		echo "Good link"
		Link_libGL32="Good Link"
	else
		echo "Broken link"
		Link_libGL32="Broken Link"
	fi
elif [ -e ${Link_libGL32} ] ; then
	echo "Link_libGL32"
else
	echo "Missing"
	Link_libGL32="Missing"
fi

if [ "Link_libGL32" = "Good Link" ]; then
	COMPAT32=${COMPAT32:-yes}
elif [ "Link_libGL32" = "Broken Link" ]; then
	COMPAT32=${COMPAT32:-yes}
elif [ "Link_libGL32" = "Missing" ]; then
	COMPAT32=${COMPAT32:-no}
fi
```

Well that is my idea, first check if exist /usr/lib/libGL.so, ever is a Symbolic link if exist, activate the COMPAT32 if not exist, just disable the COMPAT32. well i don't know if this works fine, but i hope you considere to add my idea and improve it :)

I have not have much experience with bash, but i hope this help you some way :D for help all users using your script :D

**Comment by dslackw** [comment]
Thank you very much for your time, your suggestions, your thoughts and concerns. I will study them and I will do.

**Comment by inukaze** [comment]
Many thanks to you, and to all the developers and collaborators who take into account the suggestions that we can give the taxpayers to improve this software
