### ISSUE TITLE
using sbosrcarch as secondary repository for source files

### ISSUE THREAD

**Issue by travis-82** [dslackw/slpkg#82]
Sbotools already has this featurer. It would be nice if slpkg let users to choose sbosrcarch as a centralized repository for source files.

**Comment by dslackw** [comment]
Ok Thank you, I will see what I can do.

**Comment by dslackw** [comment]
Ok @travis-82 done. It will be available in the next release.

**Comment by travis-82** [comment]
Great. I'm looking forward to test it.

**Comment by dslackw** [comment]
New release v3.2.7 it's available now you can test it. Please don't forget to tracking the new configuration files and report to me any bug.
Thank you!

**Comment by travis-82** [comment]
Thanks, I will do that.

**Comment by travis-82** [comment]
Worked fine here. But I think it's better for slpkg to search for sources in sbosrcarch by their md5 rather than their names.
