### ISSUE TITLE
Replacing alien repository

### ISSUE THREAD

**Issue by travis-82** [dslackw/slpkg#83]
Alien Bob default repository is http://bear.alienbase.nl. This repo is more speedy and has bigger bandwidth. Please consider replacing taper.alienbase with this one.

**Comment by dslackw** [comment]
Thank you very much @travis-82

**Comment by travis-82** [comment]
You're welcome. Note that according to https://rlworkman.net/pkgs/ Roby recommends using his repository through Darren Austin mirror (ie: http://slackware.uk/people/rlworkman/14.2/). Although users can add this repo to slpkg thanks to your great works. But it's better to make it default.

**Comment by dslackw** [comment]
Ok done, Thanks again @travis-82
