### ISSUE TITLE
Problem Upgrading GeoIP 1.6.10

### ISSUE THREAD

**Issue by bhreach** [dslackw/slpkg#86]
slpkg does not seem to be able to download Geo* files from sourceforge.net?

I had to download the data files manually and I guessed to put them in /tmp/slkpkg/build/_SOURCES/ after renaming the old ones that were in there.

Voila, it worked and GeoIP was upgraded to 1.6.10.

**Comment by dslackw** [comment]
Slpkg use wget for download. Works for me.

**Comment by bhreach** [comment]
I have wget. 

How can I find out what is different about my setup that prevents the downloads from working?

**Comment by bhreach** [comment]
I think you can consider this issue closed.

I removed GeoIP and reinstalled it and this time it downloaded the files without a problem.

It must have been a temporary problem with sourceforge.
