### ISSUE TITLE
[feature request] Support for custom repositories

### ISSUE THREAD

**Issue by websafe** [dslackw/slpkg#9]
First - thanks for slpkg :-) It would be great to have support for custom repositories (of slackbuilds) without the need of altering `slpkg/repositories.py` and other files. Maybe a good starting point would be a set of rules a custom slackbuild repo should follow?

**Comment by websafe** [comment]
Thank you @dslackw , this looks promising. `slpkg` will now be able to install binary packages located in custom repositories, as long it finds the `PACKAGES.TXT` file? I'm not sure how important the `ChangeLog.txt` is, but I'm still testing :-)

What I really want to achieve is to have my own slackbuilds.org-compatible repository of slackbuild scripts, and I would like `slpkg` to be able to use this repo for building from source.

A few weeks ago I've created [sbrepocombinator](https://github.com/websafe/sbrepocombinator), which simply merges my repos (listed in [repos.conf](https://github.com/websafe/sbrepocombinator/blob/master/repos.conf)) into a local clone of the slackbuilds.org repo and then I was pointing `sbopkg` to use this local repo. I did this, because I've upgraded/changed some slackbuilds found in the official repo (upgraded here: https://github.com/websafe/sbo-updates) and sbopkg has no "fall-back" mechanism, that would use the slacbkuild found in repo B if it's not found in repo A, which I needed. After that I found `slpkg` and decided to switch to it.

It would be great, if `custom-repositories` had an additional column, something like "FORMAT" where we can set if the repo is a repo of binary packages, or a repo of slackbuilds (like slackbuilds.org), and maybe other formats would be required, so I would be able to do something like this:

https://github.com/dslackw/slpkg/blob/master/conf/custom-repositories
~~~~
# This file is used to read, write and remove custom repositories by
# the user. The repositories will be added here should have a different
# name from existing repositories and the default. Also, the link must
# contain the PACKAGES.TXT files, CHECKSUMS.md5 and optional ChangeLog.txt.
# -------------------------------------------------------------------------
#
# NAME     FORMAT          URL
websafe    sbo             https://github.com/websafe/slackbuilds
updates    sbo             https://github.com/websafe/sbo-updates
~~~~

`sbo` stands, in this case,  for a slackbuilds.org-compatible repository of slackbuild scripts. 
Of course this example is not really correct, because the shown urls are missing `SLACKBUILDS.TXT` files, but I'm working on this ;-)


I've mentioned here something about a missing "fall-back" mechanism in `sbopkg`, I have to do some testing, but, assuming `slpkg` would be able to have slackbuilds.org-compatible repos in `custom-repositories`, how will the order of repos in https://github.com/dslackw/slpkg/blob/master/conf/slpkg.conf => `REPOSITORIES=slack,sbo` be handled?

It would be great (at least for me ;) to have it this way:

~~~~
REPOSITORIES=updates,websafe,sbo,slack # 1,2,3 are slackbuilds.org-compatible
~~~~

And when I do something like
~~~~
sbo -s updates,websafe,sbo Net-SSLeay
~~~~

it should build `Net-SSLeay` using the slackbuild found in the `updates` repository (because it's there and in `sbo`, but `updates` is listed before `sbo`). Or even better without the repos listed after `-s`, because they're already setup in `slpkg.conf`.

BTW, `slpkg` inspired me and I'm learning Python now 8-)

**Comment by dslackw** [comment]
First of all thank you for your kind words,

The next upgrade will install multiple packages are supported ie "# slpkg -s sbo pip Flask pylint brasero" and then target the custom slackbuilds repositories and maybe a few more features.

Thank you for your valuable time spent on slpkg and wish to quickly learn the Python language to be able to contribute more :)
