### ISSUE TITLE
sbo and alien are both trying to manage some packages?

### ISSUE THREAD

**Issue by bhreach** [dslackw/slpkg#92]
Using Version 3.2.7.

Let me explain the situation. I have 2 computers called date and lime. Installed Slackware64 14.2 on both. I update and upgrade slack on both directly from Slackware mirror.

I installed a large number of programs from sbo on date. I installed 3 packages (chromium-57.0.2987.98, chromium-widevine-plugin-57.0.2987.98, and libreoffice-5.2.5) from alien on date.

I installed the same 3 package from *alien.txz files on lime. I installed on lime, the *SBo.tgz packages created on date so they both have the same programs installed.

If I run
`slpkg -l alien --installed`
on both computers, I get a large list of installed packages but I only installed 3 from alien. All the other installed packages are from sbo.

The following bad behavior happens only on lime.
`slpkg -c alien --upgrade`
Upgrading:
  libxkbcommon-0.6.1      0.7.1              x86_64  1      alien         232 K

  flashplayer-plugin-25.0.0.148 25.0.0.148         x86_64  1      alien        7180 K
........................................
libxkbcommon-0.6.1 was installed from the SBo.tgz package built on date. So was flashplayer-plugin. date has the same programs installed but alien is not trying to upgrade them.

I don't know what I did wrong to make this happen. I did not change the configuration file (at least not intentionally).

How can I fix it?

**Comment by dslackw** [comment]
When you run "slpkg -l <repo>" you show all packages from repo. If add flag "--installed" then highlight with green color the installed packages on your system.
In the second part of the question when looking for packages for upgrading, slpkg looks for installed packages on your system and compares the version. You can use flag "--skip=" for except packages.
