### ISSUE TITLE
slpkg -c slack --upgrade tends to install all slackware packages from patches folder

### ISSUE THREAD

**Issue by travis-82** [dslackw/slpkg#94]
Hi Dimitris 
If users use slpkg to upgrade slackware it would install all packages from patches folder regardless of what currently installed in the system. That is weird, many people don't do full install and I think slpkg should just upgrade installed packages. That's what slackpkg does.

**Comment by dslackw** [comment]
Hi @travis-82,
Sorry for my delay, you can edit /etc/slpkg/slpkg.conf file and change variable ONLY_INSTALLED.

**Comment by travis-82** [comment]
Sorry, my bad. I didn't notice this option before.
