### ISSUE TITLE
slpkg -F   "slack" fail

### ISSUE THREAD

**Issue by lupox** [dslackw/slpkg#98]
slpkg -F package

ignore the route

https://mirrors.slackware.com/slackware/slackware64-14.2/patches/packages/

Check 
slpkg -F mozilla-nss

slpkg -F mozilla-nss

Packages with name matching [ mozilla-nss ]

+==============================================================================
| Repository  Package                                                      Size
+==============================================================================
  slack       mozilla-nss-3.23-x86_64-1.txz                              1704 K

Found summary
===============================================================================
Total found 1 packages in 1 repositories.

"Ignores security patches"

https://mirrors.slackware.com/slackware/slackware64-14.2/patches/packages/mozilla-nss-3.31.1-x86_64-1_slack14.2.txz

instead

 slpkg -c slack --upgrade

 mozilla-nss-3.23        3.31.1             x86_64  1      Slack        1716 K

regards

**Comment by dslackw** [comment]
Hi @lupox,
Yes because ```patches/``` directory is not included in the repository slack.

**Comment by lupox** [comment]
That is evident.

**Comment by dslackw** [comment]
I try to remember why ```patches/``` directory is out...

**Comment by lupox** [comment]
Dear Dimitris Zlatanidis,

The email sent to lupox@lupox.tk with subject
"Re: [dslackw/slpkg] slpkg -F "slack" fail (#98)"
will be delivered as soon as possible.

Your email address is automatically added to the
recipients 'whitelist'. This means for further
emails to lupox@lupox.tk, you will not receive a delivery
notification again.

TK MAILIAS
*************************************************
Looking for a way to Protect Your Identity and 
for a great no-more-spam solution for your email
address reply@reply.github.com? Sign up for TK Mailias.

It's free! Please visit http://www.mail.tk/

**Comment by lupox** [comment]
More than 90% of dlackware changes are security patches.

**Comment by lupox** [comment]
I have tried adding it as a custom repository but it does not find changeslog.txt in patches

**Comment by dslackw** [comment]
Fixed in version 3.2.9 and also you can use the flag ```--patches``` when you want to install packages from ```patches/``` directory.
Thanks for all!!!

**Comment by lupox** [comment]
Thanks, it works but let me suggest, the convenience of using default patches, because I doubt anyone wants to do a downgrade.
