### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by baronshark** [dslackw/slpkg#99]
Hello Dimitris
Quick question... im trying to install slpkg and following the instructions on the readme file, but nothing is happening... let me tell you what I did:

I downloaded the source code slpkg-3.2.8.tar.gz, then the following:
Jean # tar xvf slpkg-3.2.8.tar.gz 
Jean # cd slpkg-3.2.8

until here everything is ok, then typing the following:
Jean/slpkg-3.2.8 # ./install.sh
Jean/slpkg-3.2.8 # 

nothing happens, What am I doing wrong? Is the package created somewhere? Do I need another file inside this folder to complete the installation?

**Comment by dslackw** [comment]
Hi @baronshark,
Do you have got root privileges?

**Comment by baronshark** [comment]
Hi Dimistris, greetings from Mexico.
Yes I do, Im the root...

**Comment by dslackw** [comment]
It works fine for me. 
You can visit slackbuilds.org repository and try it to install from there.

**Comment by baronshark** [comment]
Yes, I installed it from there and worked just fine. Why is not working from the scripts you have in here?? I think is better to install it from the site of the creator of the program...

**Comment by dslackw** [comment]
https://www.youtube.com/watch?v=VTUTdQ_XGp0&feature=youtu.be

**Comment by baronshark** [comment]
Damn... I found my error after watching the video... after uncompressing the source code I deleted it and proceeded with the rest of the steps... I never imagined the ./install.sh would require the tar file if it was extracted from there, this is kind of recursive... I thought all the required files were already in the folder... new tricks to learn in the linux world uh?

I really appreciate your help and thanks for showing me how to do it... you have a new admirer and friend from the other side of the world, thanks Dimitris!
